### ISSUE TITLE
Low text quality in the Keyboard Editor

### ISSUE THREAD

**Issue by PhaxeNor** [Xiexe/XSOverlay-Issue-Tracker#10]
**Describe the bug in detail:**
When opening the keyboard editor, the text quality in some places are pretty low compared to other places.

![image](https://user-images.githubusercontent.com/323222/74352751-40d1c800-4db9-11ea-8b7f-73f7eda5836e.png)

**Comment by Xiexe** [comment]
Closing this as the Keyboard Editor is going to be completely re-done soon.
