### ISSUE TITLE
CPU frametime metric showing incorrect values

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#105]
Shows values like 0.2 ms, which is contradictory to fpsVR with values closer to 10-16ms (populated VRChat world).

I'm running a Ryzen 7 3700X but bumped into someone with a 9700K having the same issue. 

[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5805361/output_log.txt)

**Comment by Xiexe** [comment]
Currently aware of this --

I'm actually showing Compositor CPU frametime, instead of Scene CPU frametime.

This is because Steam VR actually doesn't expose scene CPU frametime as far as I can tell, and I haven't been able to figure out how things like FPSVR are calculating it quite yet.

**Comment by Swingly6061** [comment]
Ah alright, hope you find out how to get that working, in the meantime I guess I'll keep using fpsVR for performance metrics.

**Comment by Xiexe** [comment]
Should be fixed as of the current beta branch.
