### ISSUE TITLE
Saving the wrist panel position

### ISSUE THREAD

**Issue by lmgarret** [Xiexe/XSOverlay-Issue-Tracker#108]
**Feature Description:**
Hi! I think it would be great if XSOverlay saved the wrist panel's position when it's modified, or provide an option to do so. The reasons why I always need to move the panel are the following:
- the performance panel always collides with the controller's 3d mod, making it unreadable
- I also use Holoswitch which does not allow wrist repositioning and overlaps on XSOverlay wrist panel

So everytime I start SteamVR I always have to reposition it :/

Thanks for your time!

**Comment by Xiexe** [comment]
I'll see if I can get this working cleanly. Some stuff with my setup before prevented it (awhile back), but I believe it should be okay now.

**Comment by Xiexe** [comment]
Wrist overlay position is now saved in Beta 490 between restarts
