### ISSUE TITLE
Support Deezer music player

### ISSUE THREAD

**Issue by lmgarret** [Xiexe/XSOverlay-Issue-Tracker#109]
**Feature Description:**
It'd be nice to support Deezer the way Spotify is supported (talking about the UWP app). Thanks!

**Comment by Xiexe** [comment]
Will add support for Deezer.

**Comment by Xiexe** [comment]
I've added support for Deezer, but I believe that it does not do what is required to show song titles properly. 

Currently, XSO looks at the window title of the app --  a lot of music player apps will change the window title to be the current song / artist, Deezer, however, seems to remain as Deezer. None-the-less, support is "there" in the sense that it will at the very least see the Deezer application.
