### ISSUE TITLE
Problem from Issue #9 also affecting settings menu and persisting through restarts

### ISSUE THREAD

**Issue by FreelancerB10** [Xiexe/XSOverlay-Issue-Tracker#11]
The keyboard and now also the settings menu both lock up and this persists through XSO and SteamVR restarts on build 195. The problem seems to occur in a similar manner to how it happens in Issue #9 

Attached are two log files, the first after an XSO restart and the second after a SteamVR restart.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4201678/output_log.txt)
[output_log - Copy.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4201736/output_log.-.Copy.txt)

I'll comment with another log file during the first session that does it soon in case these don't say anything.

**Comment by Xiexe** [comment]
Hotfixed build 196
