### ISSUE TITLE
Cannot see HP Reverb G2 controller status

### ISSUE THREAD

**Issue by lmgarret** [Xiexe/XSOverlay-Issue-Tracker#110]
**Describe the bug in detail:**
In the wrist panel, there is no info about the cotrollers' remaining charge when I hover their icons (and the index base stations icons are useless in this case). But in the compact mode I can see the remaining battery, which is an average for both controllers I guess?

**Provide steps to reproduce the bug:**
Use a HP Reverb G2
Open the wrist panel.
Hover the controllers' icons 
See no status/battery info :/

**Expected behavior:**
Seeing the remaining battery for both controllers

**Output Log:**
(I'll edit my issue today and provide it) 
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

**Additional Information:**
Please tell me if you need more info, I'd be glad to help test changes :)

**Comment by Xiexe** [comment]
The percentage on compact is average for both, yes.

It's strange that it calculates that, but doesn't show the individuals. It might think you're using Oculus, as that is the only platform I can't show battery info for.

I'll look into this today / tomorrow, as there are other battery related issues being reported as well.

**Comment by Xiexe** [comment]
Alright, I've determined that this is the same issue that was happening with Pimax. I'm going to ask you to to provide a log once build 495 goes to the public beta branch, as it will help me determine how I need to work around the issue.

**Comment by Xiexe** [comment]
Actually, I came up with a rather elegant fix that should work in all cases, testing now, will close this issue and let you know if it works.

**Comment by Xiexe** [comment]
seems to work for pimax which likely means it should fix the issue with all HMDs. Will be on beta later tonight at some point!

**Comment by lmgarret** [comment]
Great news, thanks for your work! I unfortunately cannot use my reverb for a month, but I'll make sure to test the fix when I can :)
