### ISSUE TITLE
FPS monitoring 

### ISSUE THREAD

**Issue by lmgarret** [Xiexe/XSOverlay-Issue-Tracker#111]
**Feature Description:**
I'm not sure whether this has already been asked, sorry if it's a duplicate. 
I think it would be nice to have a FPS counter in the wrist's performance panel ? Please let me know your thoughts :)

**Comment by Xiexe** [comment]
This is something I do plan to do, frametime is essentially FPS.

Frametimes are just 1 / FPS, and FPS is the inverse of that, so 1 / frametime = framerate.

I.E. 1/0.00694 = 144

**Comment by lmgarret** [comment]
Maybe then just a toggle in the settings to display either value? As displaying both wouldn't be that useful in the end

**Comment by Xiexe** [comment]
Frametime Bar will now show framerate and frametime at the same time, as both fit on the bar nicely.
