### ISSUE TITLE
Controller percentages only work with minimal wrist overlay when using Pimax

### ISSUE THREAD

**Issue by Rexios80** [Xiexe/XSOverlay-Issue-Tracker#113]
**Describe the bug in detail:**
When using my Pimax, controller percentages only work on the minimal wrist display. The larger wrist overlay gets the percentages fine when using my Index.

**Provide steps to reproduce the bug:**
1. Use a Pimax (hard I know)
2. See that the controller percentages don't work on the large wrist overlay
3. Switch to minimal wrist overlay and the percentages work

**Expected behavior:**
The controller percentages show on the large wrist overlay while using a Pimax

**Output Log:**
[output_log_2021-03-10__12.41.58.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6117837/output_log_2021-03-10__12.41.58.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6117840/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6117841/uDesktopDuplication.log)

**Comment by Rexios80** [comment]
Update: I have a friend that uses a Rift S and he has the same issue. Maybe it's related to headsets that aren't native to SteamVR?

**Comment by Xiexe** [comment]
This should be fixed for Pimax as of build 495+, which will be going to the beta branch before the end of the day.

As for Oculus, I can't get battery information for Oculus devices, as they don't report that information to SteamVR.
