### ISSUE TITLE
Overlay Resource Monitor Showing The Wrong GPU

### ISSUE THREAD

**Issue by andyad8865** [Xiexe/XSOverlay-Issue-Tracker#114]
**Describe the bug in detail:**
When using the overlay it in VR, it displays the stats for the wrong GPU, in this case it shows the information for (GPU 2)

My system has 3 GPU's
(GPU 0 / PCI bus 0 device 2/Integrated CPU Graphics) Intel(R) UHD Graphics, 
this is used for general apps to take the load off my VR GPU
(GPU 1 / PCI bus 1) NVIDIA GeForce GTX 1080, this is the GPU I use for VR apps and games
(GPU 2  / PCI bus 2) NVIDIA GeForce GTX 750 Ti, this is used as a general use GPU for rendering blender or OBS in the background

**Provide steps to reproduce the bug:**
1) Have 2 or more Nvidia GPU's in your computer (it appears)
2) Launch The Overlay

**Expected behavior:**
For the overlay to show the information for the GPU that is being actively used for VR aka (GPU 2).

**Output Log:**
[output_log_2021-03-11__23.54.51.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6126975/output_log_2021-03-11__23.54.51.txt)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6127048/uDesktopDuplication.log)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6127049/uWindowCapture.log)

**Comment by Xiexe** [comment]
I'm aware of this issue and have been thinking of ways to solve it automatically --- 

I believe that displaying the GPU with the highest amount of usage would probably be enough, instead of taking the GPU at the 0th index only.

**Comment by Xiexe** [comment]
This should be fixed on Beta 490, please let me know!

Will be closing this issue if no response before I put the build on live in the next few days!

**Comment by andyad8865** [comment]
can confirm fixed in beta 490, thanks

**Comment by jukefr** [comment]
i have an integrated gpu on my processor and a dedicated gpu and its showing the cpu one... all at 0%
was there a regression related to this ?
(running a ryzen 9 with gtx 1070)
