### ISSUE TITLE
Auto Start with SteamVR

### ISSUE THREAD

**Issue by andyad8865** [Xiexe/XSOverlay-Issue-Tracker#116]
For the ability if possible for the app to be able to start when Steam VR is launched, i have seen this done with "Turn Signal" tho not sure if the programming here would be a limitation.

**Comment by Xiexe** [comment]
You can already auto start with SteamVR!

Just navigate to this page in the SteamVR Settings, and you'll see it in the list here!
![image](https://user-images.githubusercontent.com/5119787/111792095-46da8800-889a-11eb-982f-4ba07c3da093.png)
