### ISSUE TITLE
Playing a song with Cyrillic script in its info can cause a crash

### ISSUE THREAD

**Issue by FreelancerB10** [Xiexe/XSOverlay-Issue-Tracker#12]
Playing a song with Cyrillic in the info displayed by the wrist overlay causes XSO to crash. When trying to determine what specific character caused a crash, no individual character made it crash. No combination of characters from this title (that wasn't just the full title) that I tried would consistently crash, but some would once or twice. The title of the song that always crashes me is Профессор Лебединский Я танцую пьяный на столе as also seen in the attached log.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4204113/output_log.txt)
[error.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4204120/error.log)
[crash.zip](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4204121/crash.zip)

**Comment by Xiexe** [comment]
wtf?

**Comment by Xiexe** [comment]
Fixed in build 200+ (I think, works locally)
