### ISSUE TITLE
Left dominant hand in wrong location

### ISSUE THREAD

**Issue by DrPotatoNet** [Xiexe/XSOverlay-Issue-Tracker#125]
**Describe the bug in detail:**
If your dominant hand is set to "left" then it will be upside down and under the wrist on your right hand (it's the correct hand, but it's upside down and under the wrist).

**Provide steps to reproduce the bug:**
Change dominant hand to left and look at your right wrist.

**Expected behavior:**
It act like the right dominant hand

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6249672/output_log.txt)

**Additional Information:**
None

**Comment by Xiexe** [comment]
Known, will be fixed in next patch. 

You can move the wrist overlay manually for now. You may need to turn on "Allow Movement" under the wrist overlay settings menu.

**Comment by Xiexe** [comment]
This should be fixed as of build 502
