### ISSUE TITLE
Wrist display upside down and on bottom side of wrist

### ISSUE THREAD

**Issue by Lezreth** [Xiexe/XSOverlay-Issue-Tracker#126]
Starting yesterday, 01 April 2021, the wrist display appears on the underside of the wrist and is flipped upside down.  The overlay screens appear in the correct orientation, but all of the interface controls (keyboard, settings panel, etc.) appear upside down.  Grabbing them flips them back to correct orientation, but the wrist menu does not change.

**Comment by Xiexe** [comment]
This is an issue when having the Dominant hand set to the Left hand, as it will put the wrist on the right - the temporary fix for this is to just move the wrist overlay while in layout mode and flip it manually. The position and rotation should save. I will have a fix for this out at some point soon, hopefully. 

Sorry about that!

**Comment by Xiexe** [comment]
Fixed as of build 502
