### ISSUE TITLE
Settings button does not work/open

### ISSUE THREAD

**Issue by ScruffyRules** [Xiexe/XSOverlay-Issue-Tracker#13]
**Describe the bug in detail:**
Settings do not open

**Provide steps to reproduce the bug:**
I have no idea

**Expected behavior:**
What do you expect to happen, rather than what does happen?
Settings open

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4204470/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4204475/uWindowCapture.log)

**Additional Information:**
There's a video I have uploaded to the Discord's Bug Discussion channel.

**Comment by Xiexe** [comment]
Hopefully fixed build 200+
