### ISSUE TITLE
[beta] Performance view overlaps with main area of wrist display

### ISSUE THREAD

**Issue by bdunderscore** [Xiexe/XSOverlay-Issue-Tracker#132]
**Describe the bug in detail:**
The performance tab that can be opened on the right of the wrist display overlaps with the wrist display's normally-displayed section; depending on angle, which one is on front changes.

**Provide steps to reproduce the bug:**

1. Enter edit mode
2. Open performance tab
3. Tilt wrist

**Expected behavior:**
Performance tab should not overlap the main portion of the wrist display.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6329690/output_log.txt)

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment]
Known issue, just wasn't fixed before this beta went out because the UI is going to be overhauled for the performance status more than likely!

**Comment by Xiexe** [comment]
Fixed in the new build, rolling out soon!
