### ISSUE TITLE
[beta] Please restore the time-from-start-in-seconds data to the wrist display

### ISSUE THREAD

**Issue by bdonlan** [Xiexe/XSOverlay-Issue-Tracker#133]
**Feature Description:**
On the latest beta, the wrist display had a time-elapsed from startup display, which I found useful. Please bring it back (potentially as an option in the wrist display settings, if desired)

**Additional context:**
N/A

**Comment by Xiexe** [comment]
Known and will be restored, was an oversight :)

**Comment by Xiexe** [comment]
Restored on the new build coming out soon!
