### ISSUE TITLE
Wrist Clip Angle slider shouldn't have a minimum value of 0

### ISSUE THREAD

**Issue by P4tr0ll** [Xiexe/XSOverlay-Issue-Tracker#134]
I encountered this when trying the app for the first time and playing with the settings.

**Describe the bug in detail:**
Setting Wrist Clip Angle slider to 0 makes the wrist UI not be able to appear anymore and I believe it's only fixable by manually editing overlaySettings.json in %AppData%. EDIT: or using a keybind to open up the settings.

**Provide steps to reproduce the bug:**
Settings -> Wrist -> Clip Angle -> set slider to 0

**Expected behavior:**
The slider should have a minimum value of some positive number like 10 or 20

**Comment by Xiexe** [comment]
Clamped minimum angle to 10 degrees in the upcoming build, will be released soon.
