### ISSUE TITLE
[beta] WristUI media buttons can be pressed while hidden

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#135]
WristUI media buttons can be pressed while hidden.

Video example:
https://user-images.githubusercontent.com/50369014/115147316-b0e17b00-a05a-11eb-9e51-37aa52e76eb1.mp4

**Comment by Xiexe** [comment]
This will be fixed here in a few minutes when the new build goes out!
