### ISSUE TITLE
[docs] Themes directory is incorrect in the documentation

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#136]
https://xiexe.github.io/XSOverlayDocumentation/#/Themes

"[XSOINSTALLDIRECTORY]/XSOverlay_Data/StreamingAssets/Themes/"
should be 
"[XSOINSTALLDIRECTORY]/XSOverlay_Data/StreamingAssets/Plugins/Themes"

**Comment by Xiexe** [comment]
Good catch, will update this now!
