### ISSUE TITLE
General frametime not affected by CPU frametime

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#140]
The brief frametime/framerate indicator only uses GPU frametime, instead of the highest of either GPU or CPU. 

**Steps to reproduce the bug:**
Get higher CPU frametime than GPU frametime (pretty common in VRChat)

**Additional**
General FPS indicator showing around 200FPS
![vrmonitor_nw6rJuNNLM](https://user-images.githubusercontent.com/50369014/115626453-cf1ad580-a2fd-11eb-97ed-4b271c2e4216.png)

Here you see CPU time is closer to 60FPS. 
![vrmonitor_zZfbxpPtnJ](https://user-images.githubusercontent.com/50369014/115626462-d04c0280-a2fd-11eb-8a97-b604a19e73d9.png)

**Comment by Xiexe** [comment]
Should now show a combination of both in the next beta build.
