### ISSUE TITLE
Media wrist menu buttons do not work in beta

### ISSUE THREAD

**Issue by AmaliaKalio** [Xiexe/XSOverlay-Issue-Tracker#142]
**Describe the bug in detail:**
XSO is successfully attaching to my media player (Foobar). However, the previous/next/play/pause buttons are not something I can interact with.

**Provide steps to reproduce the bug:**
1) Run XSO
2) Run Foobar
3) Restart either
4) Reattempt in any order of your choosing

**Expected behavior:**
Media function button should function

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.
[output_log_2021-04-26__18.53.19.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6381307/output_log_2021-04-26__18.53.19.txt)

**Additional Information:**
Buttons worked just after launch of the new UI layout, but currently do not.

**Comment by Xiexe** [comment]
This is known and an issue with the current beta build as of last Friday -- Should have a fix out tonight with some other stuff, just finishing up before pushing the build out!

**Comment by Xiexe** [comment]
Dropping this here: Going to be delaying that beta release until tomorrow sometime due to some issues that cropped up with it!

**Comment by Xiexe** [comment]
Should be fixed on the latest beta build, 515.
