### ISSUE TITLE
Low tracker battery notification false-positive

### ISSUE THREAD

**Issue by AmaliaKalio** [Xiexe/XSOverlay-Issue-Tracker#144]
**Describe the bug in detail:**
XSO will pop up low battery warnings for body trackers as they are connected, despite the wrist overlay showing them to have a decent charge. (In this case, all are 93% or higher.)

**Provide steps to reproduce the bug:**
1) Start SteamVR
2) Start XSO (If not already running)
3) Turn on a body tracker

**Expected behavior:**
What do you expect to happen, rather than what does happen?
No notification should be presented for low-battery warnings, if there isn't a low battery.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.
[output_log_2021-04-27__17.17.21.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6387970/output_log_2021-04-27__17.17.21.txt)

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment]
Thanks for this, knew about it but forgot since nobody made a proper ticket for it. Will get this fixed tomorrow.

**Comment by Nono-VR** [comment]
Initializing trackers should no longer trigger low batter notifications.
