### ISSUE TITLE
[515] Frame time on wrist overlay not displaying correctly.

### ISSUE THREAD

**Issue by FreelancerB10** [Xiexe/XSOverlay-Issue-Tracker#147]
The frame time on the System Performance window of the wrist overlay seems to be displaying an incorrect number. Numbers listed when clicked into it seem proper.

Example video:
https://user-images.githubusercontent.com/33292749/116554010-b6e02300-a8c8-11eb-89a0-d576d942d48b.mp4

**Comment by Xiexe** [comment]
FT was changed to be the total of CPU + GPU combined as a test. I can instead swap it to be one or the other based on what's higher.

**Comment by Nono-VR** [comment]
Frame time now returns the max value between CPU and GPU.
