### ISSUE TITLE
HTC 2.0 trackers do not show as off when out of battery or turned off due to inactivity 

### ISSUE THREAD

**Issue by JackW-P** [Xiexe/XSOverlay-Issue-Tracker#149]
The overlay does not show HTC 2.0 trackers as off when they run out of battery, or when then turn off due to inactivity.

Let the trackers run out or turn off on their own. I have spoken to a couple others who have XSOverlay but don't seem to have this issue however. 

The tracker icons are supposed to turn black when the trackers run out of battery or turn off otherwise. They instead stay in whatever state they were in when they turned off (i.e. on if they had power, or flashing in the low battery mode)

Here is a screenshot of the overlay with all trackers turned off (out of battery) but still showing as on but low power. 
![Screenshot (5)](https://user-images.githubusercontent.com/55803812/116878940-ecae4000-ac17-11eb-820f-75381e6a8141.png)

[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6414958/output_log.txt)

**Comment by Xiexe** [comment]
Looking in to this

**Comment by JackW-P** [comment]
Ah that's unfortunate, but glad the issues is at least known now. Hopefully a steamvr update will come soon to fix this issue then

**Comment by RheaAyase** [comment]
Here is a stupid workaround idea - display the 3 highest % trackers first? Like really just order descending :D

**Comment by JackW-P** [comment]
As there's no explicit identifier for what each tracker is assigned to (left foot, right foot etc) I turn mine on in a specific order so I know which is which in the overlay, so this would be confusing me at at least. Fox for that is more a feature suggest ion anyways so I won't divulge unto that here.

**Comment by RheaAyase** [comment]
All trackers should have roughly similar charge, if one dies, the rest becomes useless. Unless you want to make up the potential difference of 5% by charging one tracker for 10 minutes :D

**Comment by JackW-P** [comment]
(didn't mean to close lmao)
That's fair, but occasionally my waist tracker will die while the other trackers still have 20-30% in them which is irritating, so knowing which is which is still nice. Would also tell me if I forgot to charge one or if one isn't charging using my external batteries which also happens.

**Comment by Nono-VR** [comment]
So here is the problem, if a tracker is powered on at all during a steam vr session it will return as on with what ever its last battery percentage was even if it is powered off. So hypothetically say you had 6 trackers and all of them where changing when you started your SteamVR session, you turn three off for later and used other other three. If you track all six only display the three highest charged then you would only ever see the three 100% tracker as they are staying cashed in the data SteamVR returns to us. You could work around this if we were to do what you suggest and you made sure that only three were initially registered in the SteamVR session until your wanted the other three, but that is really not a reasonable expectation for most users. Really what I was trying to do as a first step was just deregister off or standby devices, that should have covered all the cases, and that is what used to happen, but yeah bad data for now.

**Comment by RheaAyase** [comment]
The only issue I'd see is when doing a performance with 10 point tracking. Ain't got 7 slots to show battery for all of them eh? But that's a whole another can of worms that is beyond the scope of XS Overlay.
