### ISSUE TITLE
Unable to switch with 2 different resolution monitors

### ISSUE THREAD

**Issue by Univeri** [Xiexe/XSOverlay-Issue-Tracker#15]
**Describe the bug in detail:**
An issue with 2 different resolution monitors and when switching to the 1080p, you can no longer switch back to the 1440p one. The cursor is incapable of reaching the settings button to switch. 

**Provide steps to reproduce the bug:**
Switch to a smaller resolution monitor from a larger one. 

**Expected behavior:**
Expect to hit settings button in order to switch back to 1440p or larger monitor. 

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4223097/output_log.txt)

**Additional Information:**
This did not happen previously, Problem appeared with new steamvr dashboard.

**Comment by Xiexe** [comment]
This is interesting, I actually have a primary 1440p display and two secondary 1080p displays and haven't run into this. I'll look into it more for the next build. :)

**Comment by Xiexe** [comment]
Fixed in next build. Same bug as the what happens when attaching a device to your hand and scaling it.
