### ISSUE TITLE
Problems with opening new windows

### ISSUE THREAD

**Issue by xBri0nc** [Xiexe/XSOverlay-Issue-Tracker#154]
So I just recently got XSOverlay, and I got this problem when trying to change the screen for my window. It does know that there are other tabs and my other screen, but does not preview them. 

When I tried to click on the other tabs and my other screen, the window just disappears and sometimes the edit tab also disappears. I tried restarting my PC a couple of times but it did not work.

I expected to show the application and other screen I chose, but it does not.

**Output Log:**
[output_log_2021-05-09__08.35.22.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6447885/output_log_2021-05-09__08.35.22.txt)

**Comment by Xiexe** [comment]
Hi, would you mind trying out the beta branch to see if the issue persists, and, if it does, would you mind sending the log from the beta branch as well?

You can change to the beta branch by right clicking XSOverlay in Steam > Properties > Betas > Set Drop-down to beta-

**Comment by xBri0nc** [comment]
Yeah, let me try that.

**Comment by xBri0nc** [comment]
I just tried it and it still persisted.  The window disappears and when I try to go to my other monitor, it freezes on the first monitor, just like before.

[output_log_2021-05-09__14.44.11.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/6448475/output_log_2021-05-09__14.44.11.txt)

**Comment by Xiexe** [comment]
Hmm, from the log it looks like the null error is fixed, however, it seems like your monitor is unsupported by the desktop duplication API, it does attempt to fall back to the BitBlt capture, and it is getting all the monitor information correct after that. 

I'm assuming you're using a laptop that uses Nvidia Optimus based on the specs?

It should, again, be falling back based in the log. I'll look into it a bit further though.

**Comment by xBri0nc** [comment]
Yes I am, it is a Lenovo gaming laptop, but I don’t know much about the specs of it. And yes, My laptop does use Nvidia Optimus.

**Comment by Xiexe** [comment]
I pushed a new beta branch last night, give it a shot and let me know if that works for you.

**Comment by Xiexe** [comment]
Closing this since it was resolved!
