### ISSUE TITLE
[SQU-293] (Beta) Make the time section smaller (change it's layout)

### ISSUE THREAD

**Issue by DrBlackRat** [Xiexe/XSOverlay-Issue-Tracker#169]
I'm in the beta and I like the new UI but I find it kinda annoying, how much space that row in the middle with the time in it takes up, especially because there is so much empty space on the left and right side of it.

Btw because the menu would get thinner that way, maybe make the media control buttons viable at all time, right under where it says what is playing.

![](https://uploads.linear.app/2f1c7d43-8759-4c1e-9b39-e2f0acd0f409/780802d1-78cd-48e0-858e-06c067a37153/267f9d0b-29cb-469a-9810-2f41c80f831c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmMWM3ZDQzLTg3NTktNGMxZS05YjM5LWUyZjBhY2QwZjQwOS83ODA4MDJkMS03OGNkLTQ4ZTAtODU4ZS0wNmMwNjdhMzcxNTMvMjY3ZjlkMGItMjljYi00NjlhLTk4MTAtMmY0MWM4MGY4MzFjIiwiaWF0IjoxNjkzNDQ2ODI2LCJleHAiOjE2OTM1MzMyMjZ9.1ALBckV7XpW67ZiZ1cW845LMHtDMd5PaWps6KxCXw6Y)

<sub>From [SyncLinear.com](https://synclinear.com) | [SQU-293](https://linear.app/square-hole-interactive/issue/SQU-293/beta-make-the-time-section-smaller-change-its-layout)</sub>

**Comment by Xiexe** [comment]
Done as of latest betas.
