### ISSUE TITLE
[SQU-292] Ability to Change Cursor Size

### ISSUE THREAD

**Issue by MMMaellon** [Xiexe/XSOverlay-Issue-Tracker#171]
**Feature Description:**
The ability to change the size of the blue dot that acts as a cursor or hide it or change it to something like a mouse icon so that the click happens in the corner of the cursor not the center.

**Additional context:**
I have 4k monitors which means the blue dot covers up 4x as much area as it would on a 1080p monitor unless I scale my monitors up 4x in VR. The dot might be necessary in places where the mouse cursor is not visible such as the settings menu, but the size of it, makes it difficult to click buttons and highlight text.

I realize I can just scale my windows up in 3d space, but it's far too cumbersome to have to constantly scale my windows up and down. Especially when I'm working in a program like Unity where I need to be zoomed out enough to see the scene window and mess with controls in the inspector at the same time.

I took a screenshot of me trying to click the dropdown icons in Unity. The window is at a comfortable size for me in VR, but the blue dot is so large, I can't tell if I'm hovering over the dropdown icon or not.

![](https://uploads.linear.app/2f1c7d43-8759-4c1e-9b39-e2f0acd0f409/c9a9b0b0-d9b1-4648-a536-37aa11371a7f/fee36100-5ea2-4c8f-baf4-5ea248cd06a5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmMWM3ZDQzLTg3NTktNGMxZS05YjM5LWUyZjBhY2QwZjQwOS9jOWE5YjBiMC1kOWIxLTQ2NDgtYTUzNi0zN2FhMTEzNzFhN2YvZmVlMzYxMDAtNWVhMi00YzhmLWJhZjQtNWVhMjQ4Y2QwNmE1IiwiaWF0IjoxNjkzNDQ2ODA5LCJleHAiOjE2OTM1MzMyMDl9.3WskH8R5a8xrOv98D1qDhr4cVyaTpW32cccKVSXGh9M)

<sub>From [SyncLinear.com](https://synclinear.com) | [SQU-292](https://linear.app/square-hole-interactive/issue/SQU-292/ability-to-change-cursor-size)</sub>

**Comment by Xiexe** [comment]
good idea
