### ISSUE TITLE
"Old" capture api no longer captures any chrome windows

### ISSUE THREAD

**Issue by RheaAyase** [Xiexe/XSOverlay-Issue-Tracker#175]
$subject.

**Comment by Xiexe** [comment]
Old capture method is legacy and I will likely not be fixing bugs with it. It's probably going to be removed in the future as it's wildly slower than WGC.

**Comment by RheaAyase** [comment]
See, there was nothing wrong with it, meanwhile the new one is bugged beyond reason.
