### ISSUE TITLE
Low power triggers a horrible notification

### ISSUE THREAD

**Issue by RheaAyase** [Xiexe/XSOverlay-Issue-Tracker#178]
There is no toggle for that to shut it up, it's very disturbing, especially so considering that the last 15% will still last nearly an hour on index+3.0 so that notification is useless (would be useful at 10%)

**Comment by RheaAyase** [comment]
This a bug imo, an incomplete feature being introduced is a bug. And very annoying and disturbing one at that.

**Comment by Xiexe** [comment]
You are requesting for a feature to be altered, a sound effect is not a bug. 

Therefore, it is a feature request. The feature of "notify when things have low battery" works perfectly fine. You just don't like the sound.

You can change the sound. The sound is located in `[XSOInstallDirectory]/XSOverlay_Data/StreamingAssets/Etc/Audio/`  and called "lowBattery.ogg", any replacement must be named that, and must be in ogg format.

Please don't try and argue semantics with me, thats not a way to get me to change something, and, in fact, coming at me with semantics and an attitude about it is a way to make me *not* want to change it, or take anything you request seriously. 

Just FYI, I was going to add a toggle for the sound on the notification already. No need for the attitude.

**Comment by Xiexe** [comment]
Added a toggle for low battery sound and a slider to choose what percentage the notification gets sent in the next update. Beta should be out tonight some time. 

Try not to be so moody with future issues. :)

**Comment by RheaAyase** [comment]
I don't see trying to explain severity of an issue for you to perhaps better prioritize as being moody. Let's not read between the lines what isn't actually said :p
