### ISSUE TITLE
Add an option to ignore the aim mode when grabbing an overlay directly.

### ISSUE THREAD

**Issue by TCL987** [Xiexe/XSOverlay-Issue-Tracker#179]
**Feature Description:**
Overlay rotation gets unstable when grabbing an overlay directly with your hand (i.e. your hand is very close to the overlay). A hybrid mode that suppresses the aim at behaviour when your hand is close to the overlay would avoid this issue and would make manipulating overlays more intuitive.

**Comment by Xiexe** [comment]
yes

**Comment by Xiexe** [comment]
Overlays that are too close to the hand will now respect hand position and orientation entirely, and will resume trying to aim at a target when further away again.
