### ISSUE TITLE
About the date displayed on the watch

### ISSUE THREAD

**Issue by 404-not-friend** [Xiexe/XSOverlay-Issue-Tracker#181]
**Feature Description:**
Thank you for all your help and support.
Thank you for developing such a nice software.

I was wondering if it would be possible to add the day of the week to the date displayed on the watch.
Please consider it.

**Comment by Xiexe** [comment]
Yes indeed, I can add this!

**Comment by Xiexe** [comment]
Added in the next update, coming to the beta branch tonight
