### ISSUE TITLE
Keyboard blanks in Japanese localised environments

### ISSUE THREAD

**Issue by 404-not-friend** [Xiexe/XSOverlay-Issue-Tracker#182]
**Feature Description:**
Thank you very much for all your help.
Thank you for developing such a wonderful software.

Now, I would like to ask you if it is possible to display "半角/全角(Hankaku/Zenkaku)" on the upper left key when JIS keyboard is selected in Japanese localized environment.
Please consider it.

**Comment by Xiexe** [comment]
Yes! I was already planning to add buttons for IME inputs as a toggle in the keyboard options! 

This is something I was probably going to start doing today, actually!

**Comment by Xiexe** [comment]
Added in the next update, beta branch should be out tonight.
