### ISSUE TITLE
A request for low power notifications controls

### ISSUE THREAD

**Issue by FyzerVR** [Xiexe/XSOverlay-Issue-Tracker#183]
I like the idea of being able to change the threshold at witch the low battery notification happens at additionally a toggle the sound could be useful in some rare instances.

Some device batteries variety a good bit in terms of how long they last (also due to wear levels) so that 15% could mean 15 mins or a hour+ depending so having the ability to tweak this could give it more value for some.

**Comment by Xiexe** [comment]
Added in the next update.
