### ISSUE TITLE
cant interact with keys on the borders of the keyboard when I resize it

### ISSUE THREAD

**Issue by ErZiEr-7w7** [Xiexe/XSOverlay-Issue-Tracker#19]
**Describe the bug in detail:**
It happens when you make the keyboard smaller, it just stop letting you interact with the keys on the sides, bottom and top of it

**Provide steps to reproduce the bug:**
Steps to reproduce the behavior: did it twice, one with first noticed it on vrc and then restarted steamvr and happened again when i made the keyboard smaller

**Expected behavior:**
It wont let you interact with the keys on the borders of the keyboard

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4236196/output_log.txt)

**Additional Information:**
recorded the bug but couldn't upload it here, you can ask me on discord if needed (ErZiEr#1234)

**Comment by Xiexe** [comment]
Will be fixed in b205, which will drop shortly
