### ISSUE TITLE
[SQU-287] Sort tracker battery life indicator by lowest charge level

### ISSUE THREAD

**Issue by euan142** [Xiexe/XSOverlay-Issue-Tracker#205]
So I have 4 trackers, throughout the night I always have one on charge swapping out the lowest charged one I'm wearing when it gets low, allowing for a longer time in which I can have all the trackers on. The issue currently is that when I take off the first tracker to charge it still is shown in XSOverlay (as SteamVR still considers it existing, just not connected) meaning when I turn on the fourth tracker it will never be shown in XSOverlay.

It would be nice if XSOverlay sorted disabled trackers to the end and sorted enabled trackers by charge level, lowest being first so I can track which needs charged first.

This would also help when more than 3 trackers are enabled and used, something likely to become less rare

<sub>[SQU-287](https://linear.app/square-hole-interactive/issue/SQU-287/sort-tracker-battery-life-indicator-by-lowest-charge-level)</sub>

**Comment by Xiexe** [comment]
Yeah currently XSO doesn't support more than 3 trackers. 

This was due to being limited in scope by implementing primarily for VRChat, and will be overhauled soon.

**Comment by Xiexe** [comment]
Done in beta.
