### ISSUE TITLE
Battery level for Quest (2)

### ISSUE THREAD

**Issue by luximus-hunter** [Xiexe/XSOverlay-Issue-Tracker#206]
**Feature Description:**
I'd like to request a feature to see the battery level of the Quest (2) and it's controllers. Currently the controllers shown are the index controllers (i think) and 3 full body trackers. I'd like there to be support for the Quest (2), and in the future more headsets.

**Additional context:**
Instead of the 5 current devices being tracked, it could display 3 devices: the Quest (2) and it's 2 controllers.

**Comment by nnaaa-vr** [comment]
We'd also like to have battery information for Oculus devices. Unfortunately, Oculus does not make this information available through interfaces to its runtime, and so OpenVR's wrapper around it has no way to query battery information from Oculus devices. In turn, we're also unable to query this information.

**Comment by luximus-hunter** [comment]
So there is absolutely no way or workaround to get this information?

**Comment by nnaaa-vr** [comment]
Not that I'm aware of. Other overlay products also don't display battery levels for Oculus devices for the same reason, to my knowledge.

**Comment by luximus-hunter** [comment]
Is this something that might work?

https://forums.oculusvr.com/t5/Unity-VR-Development/How-to-get-Oculus-Quest-2-Controller-Battery-in-Unity/td-p/890017

**Comment by luximus-hunter** [comment]
I see i see. Well, that's a bit sad then. Maybe in the future oculus will allow a readout of battery levels, as it's used in their own apps. We'll see.

**Comment by nnaaa-vr** [comment]
Yeah I'd like that too, we certainly have a lot of Quest users it'd benefit. Thanks.
