### ISSUE TITLE
Minimal Wrist Display Bug

### ISSUE THREAD

**Issue by Zeonymous** [Xiexe/XSOverlay-Issue-Tracker#207]
**Describe the bug in detail:**
The "Minimal Wrist" toggle does not show the battery life on startup.

**Provide steps to reproduce the bug:**
Toggle Minimal Wrist, and restart XSOverlay.

**Expected behavior:**
What do you expect to happen, rather than what does happen?
Minimal Wrist should show the battery life on fresh-boot.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

[output_log_2022-02-05__11.52.34.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008535/output_log_2022-02-05__11.52.34.txt)
[output_log_2022-02-05__06.37.00.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008536/output_log_2022-02-05__06.37.00.txt)
[output_log_2022-02-04__08.13.07.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008537/output_log_2022-02-04__08.13.07.txt)
[output_log_2022-02-03__23.09.53.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008538/output_log_2022-02-03__23.09.53.txt)
[output_log_2022-02-03__10.45.47.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008539/output_log_2022-02-03__10.45.47.txt)
[output_log_2022-02-03__08.22.55.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008540/output_log_2022-02-03__08.22.55.txt)
[output_log_2022-02-02__04.19.45.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008541/output_log_2022-02-02__04.19.45.txt)
[output_log_2022-02-01__20.05.59.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008542/output_log_2022-02-01__20.05.59.txt)
[output_log_2022-02-01__19.52.15.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008543/output_log_2022-02-01__19.52.15.txt)
[output_log_2022-01-31__18.50.13.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8008544/output_log_2022-01-31__18.50.13.txt)

**Comment by Xiexe** [comment]
Minimal wrist no longer exists as of the UI 3.0 redesign as it's not needed.
