### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by TARDIS76** [Xiexe/XSOverlay-Issue-Tracker#210]
notifications dont work? I don't get my discord notifications while in game vrchat but I can hear them the test notifications work fine but when messaged on discord I do not they the notification ping. I have no idea why I do not see my notifications when I get a message from discord

**Comment by Xiexe** [comment]
resolved on discord

**Comment by Erallie** [comment]
@Xiexe What is the solution? I'm having this problem too.

**Comment by Xiexe** [comment]
> @Xiexe What is the solution? I'm having this problem too.

Notifications in XSO are just received from other applications that interact with XSOs API.

If you want notifications for something like discord you'll need to have an application that supports doing that.

There are a few apps that attempt to mirror all notifications from the windows Notification Center. That usually works pretty well.

**Comment by Erallie** [comment]
@Xiexe Can you link to some apps that mirror all notifications from the windows Notification Center?

**Comment by Erallie** [comment]
Nevermind! I found [XSOverlay Notifier](https://github.com/bluskript/xsoverlay-notifier), which works great! Thank you!

Edit: XSOverlay Notifier was a bit broken, so I fixed it up and am using my fork now, called [XS Notify](https://github.com/Erallie/xs-notify).
