### ISSUE TITLE
ExternalMessageAPIConfig.json missing from config folder; OSC implementation in VRChat not working

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#213]
**Describe the bug in detail:**
The file `ExternalMessageAPIConfig.json` is missing (doesn't appear to be generating anymore) from `[XSOINSTALLDIRECTORY]/XSOverlay_Data/StreamingAssets/Plugins/Config/` and as a result, it's OSC implementation no longer works with VRChat. I've included multiple logs from around the times I suspect the issue to have occurred possibly.

**Output Log:**
[output_log_2022-05-09__12.07.36.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8672284/output_log_2022-05-09__12.07.36.txt)
[output_log_2022-05-10__15.55.18.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8672274/output_log_2022-05-10__15.55.18.txt)
[output_log_2022-05-11__11.33.33.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/8672273/output_log_2022-05-11__11.33.33.txt)

**Additional Information:**
Multiple people, including myself have reported having been affected by this. I thought something with VRChat build `11948` might have done something as it started occurring for others around the similar time, but not sure about that at all.

**Comment by SalbugVR** [comment]
Checked through the logs, and definitely can confirm it just doesn't exist anymore after my previous session.
![image](https://user-images.githubusercontent.com/24326270/167919244-82b16426-6f00-4a5d-9c0f-6f918b298f77.png)

**Comment by SalbugVR** [comment]
It appears the bug coincides with a recent update in the beta branch which went _completely_ under the radar for me.
![image](https://user-images.githubusercontent.com/24326270/167923325-e1de5ef9-1f5f-4426-9de3-81966fc2c7fa.png)

**Comment by DrBlackRat** [comment]
It appears that this started happening after an unannounced update from around 21h ago.
![image](https://user-images.githubusercontent.com/46327609/167923546-e85d48a2-285e-4ca2-93c3-82ec312332ed.png)

**Comment by Xiexe** [comment]
Right, looks like we had a miscommunication and accidentally rolled back the OSC implementation.

I'll get a fix out tonight.

**Comment by Xiexe** [comment]
Fixed in latest open beta
