### ISSUE TITLE
Show battery level for more than 5 devices (+ extra QOL features)

### ISSUE THREAD

**Issue by sacred0** [Xiexe/XSOverlay-Issue-Tracker#214]
With the advent of VRChat's IK 2.0, it is not uncommon to have more than 3 trackers being used at once, meaning that it exceeds the limit of 5 devices that XSOverlay can display. If using 11 point tracking, the maximum supported by VRChat, there needs to be room in the UI for 10 devices, which would fill up exactly 2 rows in the current UI. There is also the possibility that _more_ than 10 devices would need to show up, like when using more trackers for motion capture, or for other tracked objects in the real world.

Here are a few suggestions:
- Add additional rows of devices when the previous is filled
- Keep it in one row, but allow either horizontal or vertical scrolling to see the rest.
- Add an "Expand" icon to expand the device list if more than 5 devices are connected

Additionally, it would be nice if the tracker icons actually corresponded to the type of tracker being used, rather than always displaying a Vive 2.0 tracker. This is something I noticed OVR Toolkit does, and would like to see that being implemented in XS.

One more thing I would like to see added is the ability to see the SteamVR tracker roles either by hovering over an icon, or directly below each tracker. With so many trackers being worn at once, it can be annoying to figure out which ones battery is running low, so this would be a very welcome feature.

I am fairly new to Github, so if you want me to split this up into multiple feature req. posts, let me know.

**Comment by TheRishabhB** [comment]
+1, would be really nice for people with more devices.

**Comment by Slvr11** [comment]
+1 for this. Even though I have tundras as my additional devices and they pretty much never die during my VR sessions, this would still be a very handy feature!

**Comment by SalamiTTP** [comment]
This would be really nice!

**Comment by Xiexe** [comment]
Done in the latest betas. You can now scroll the battery display to see more devices
