### ISSUE TITLE
[SQU-284] Battery life missing on minimum wrist feed display on start

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#218]
**Describe the bug in detail:**
Battery life on the minimum wrist feed is missing when you boot up XSOverlay

**Provide steps to reproduce the bug:**
Switch wrist feed to minimum display and restart XSO

**Expected behavior:**
Battery life should be displayed as normal

**Additional Information:**
While the battery life is missing on boot, you can have it reappear by toggling minimum display off and on again.

<sub>[SQU-284](https://linear.app/square-hole-interactive/issue/SQU-284/battery-life-missing-on-minimum-wrist-feed-display-on-start)</sub>

**Comment by Xiexe** [comment]
As of beta, minimal wrist will not longer exist, since it's basically the default, sort of.

It's redesigned.
