### ISSUE TITLE
Invert zoom (Scaling) of window direction (Push/Pull)

### ISSUE THREAD

**Issue by kenthinson** [Xiexe/XSOverlay-Issue-Tracker#228]
**Feature Description:**
Please provide a clear and concise description of the feature you want.

I would like to be able to invert the Scaling motion. Push/Pull.

**Additional context:**

It would be nice to be able to invert the scaling of the windows gesture. Example If I Grab a Window. Hold the trigger and pull. I would expect the window to come toward me. Or zoom in. The push gesture would then make the window smaller in scale. Aka zoom away. It just seems what's natural to me. So being able to toggle the direction would be cool. Thanks!

I'm not sure if I described this sufficiently well to be understood. Lots of jargon to try and explain what I am meaning. If you require I can provide a video demo.

**Comment by Xiexe** [comment]
There's already a setting for this.

Settings > Windows (Overlays on the beta) > Invert Scale Gesture
