### ISSUE TITLE
add a setting for windows to disable input in edit mode 

### ISSUE THREAD

**Issue by sophia1000** [Xiexe/XSOverlay-Issue-Tracker#23]
**Feature Description:**
im probably not alone in having a wrist display then using edit mode for a big window. i think having a setting in the window options that disables input but only when in edit mode would be useful. then it wouldn't get in the way as much like for my set up if im in edit mode in not using my wrist window at all and it just ends up in the way.

**Comment by Xiexe** [comment]
Meaning the Lock Input toggle, but only in edit mode?

**Comment by Yui-Hell** [comment]
yes so like when in edit mode the specified window cant be clicked on when in edit mode. would be very useful for when you have a wrist window open and it gets in way some times

**Comment by Xiexe** [comment]
Hmm, locking input on a window doesn't currently stop it from blocking raycasting, it will still get in the way if it's in the way. 

Unity might have something to allow raycasts to hit but also keep going through a collider, if not I can put together a system for it. 

Basically bullet penetration at that point, but for clicking. 

Ill see what I can come up with.

**Comment by Yui-Hell** [comment]
even if it still hits it but doesn't register a click would still be better. also another way you could do it is make the setting turn the window into a small button to like open the setting to unlock it kinda thing. so it kinda turns the window off and all thats there is a small button to unlock it

**Comment by Yui-Hell** [comment]
then it wouldn't really get in the way anymore if its just a small button

**Comment by Xiexe** [comment]
I'm currently in the process of a pretty big overhaul to how windows work, once I get done with that we'll see if it addresses the windows being in the way sometimes.

**Comment by Xiexe** [comment]
I believe that this was addressed, and as this issue has been inactive for some time, I'll be closing it.
