### ISSUE TITLE
xsoverlay

### ISSUE THREAD

**Issue by genedb01** [Xiexe/XSOverlay-Issue-Tracker#230]
**Describe the bug in detail:**

**Provide steps to reproduce the bug:**

**Expected behavior:**
What do you expect to happen, rather than what does happen?

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment]
I think you didn't fill out the forum. Not sure what the bug report is supposed to be about here.
