### ISSUE TITLE
Back-of-hand overlay visually blocked by Index controller

### ISSUE THREAD

**Issue by dragos240** [Xiexe/XSOverlay-Issue-Tracker#232]
**Describe the bug in detail:**
The normal wrist/back of hand overlay is blocked a bit by the curved piece of the index controller's presence in VR. I have to look around it in order to use the overlay, which is annoying.

**Provide steps to reproduce the bug:**
- Have index controller
- Turn wrist so back of your hand is visible
- Half the interface is blocked by the "arch" of the controller

**Expected behavior:**
The overlay can be seen completely without the index controller's arch masking its view.

**Output Log:**
<details> 
<summary>Logs</summary>
[XSOVR] | 10/24/2022 6:33:37 AM | Starting XSOverlay Process Manager. This is needed for the Task Tray Icon.
[XSOVR] | 10/24/2022 6:33:37 AM | Starting up...
[XSOVR] | 10/24/2022 6:33:37 AM | Build Number : 561
[XSOVR] | 10/24/2022 6:33:37 AM | 

--- SYSTEM SPECS ---

[XSOVR] | 10/24/2022 6:33:37 AM | GPU: NVIDIA GeForce RTX 2080 SUPER | VRAM: 8010 | Direct3D 11.0 [level 11.1]

[XSOVR] | 10/24/2022 6:33:37 AM | CPU: AMD Ryzen 5 5600X 6-Core Processor  | THREAD COUNT: 12 | CLOCK: 3700MHz

[XSOVR] | 10/24/2022 6:33:37 AM | SYSTEM MEMORY: 32692MB

[XSOVR] | 10/24/2022 6:33:37 AM | OPERATING SYSTEM: Microsoft Windows NT 10.0.19044.0
[XSOVR] | 10/24/2022 6:33:37 AM | 

--- END SYSTEM SPECS ---

[XSOVR] | 10/24/2022 6:33:37 AM | Loaded config file from: C:/Users/nat/AppData/LocalLow/Xiexe/XSOverlay/config
[XSOVR] | 10/24/2022 6:33:37 AM | Moving Wrist to Left Hand.
[XSOVR] | 10/24/2022 6:33:37 AM | File for Simulation controls already exists! Initializing...
[XSOVR] | 10/24/2022 6:33:37 AM | Spinning up an open UDP port to listen for notifications!
[XSOVR] | 10/24/2022 6:33:37 AM | Found External Message API Config:
{
  "UdpPort": 42069,
  "OscSendPort": 9000,
  "OscListenPort": 9001,
  "OscOutputPath": "/avatar/parameters/"
}
[XSOVR] | 10/24/2022 6:33:37 AM | UDP Port 42069 hooked!
[XSOVR] | 10/24/2022 6:33:37 AM | OSC Ports | Listen 9001 / Send 9000 hooked!
[XSOVR] | 10/24/2022 6:33:37 AM | OSC Initialized!
[XSOVR] | 10/24/2022 6:33:37 AM | UDP Listener Initialized!
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: WindowLayoutFolder
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: KeyboardOverlay
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: AppDrawer
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: WindowSettingsConfigurer
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: Toolbar (Global)
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: Toolbar (Window)
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: Notification_Popup
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: Wrist_PerfStats
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: Dashboard Overlay (Floating)
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: WristOverlay
[XSOVR] | 10/24/2022 6:33:38 AM | Creating texture for Overlay: SkipTutorialPopup
[XSOVR] | 10/24/2022 6:33:38 AM | CheckKeyboardFormat() -> "United States - dvorak" -> ANSI Format
[XSOVR] | 10/24/2022 6:33:38 AM | CheckKeyboardFormat() -> "United States - dvorak" -> ANSI Format
[XSOVR] | 10/24/2022 6:33:38 AM | CPU : amd ryzen 5 5600x 6-core processor  | ManufactererID : 1
[DRP] Starting Discord Rich Presence
[DRP] Discord Rich Presence intialized and connecting...
[XSOVR] | 10/24/2022 6:33:38 AM | Cleaning up old log files...
[XSOVR] | 10/24/2022 6:33:38 AM | Starting XSOverlay Media Handler Process.
[XSOVR] | 10/24/2022 6:33:38 AM | Attempting to load Sound pack with Index of: 0
[XSOVR] | 10/24/2022 6:33:38 AM | C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/Plugins/KeyboardSounds\Default/soundpackSettings.json
[XSOVR] | 10/24/2022 6:33:38 AM | Detected System Language: en-US
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/de
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/en-US
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/es-ES
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/fr
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/ja
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/ko
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/nl
[XSOVR] | 10/24/2022 6:33:38 AM | Found Localization Directory: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/sv-SE
[XSOVR] | 10/24/2022 6:33:38 AM | Layout Directory is: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/Layouts
[XSOVR] | 10/24/2022 6:33:38 AM | Device LeftTracker subscribed to events for LeftHand!
[XSOVR] | 10/24/2022 6:33:38 AM | Device HMD subscribed to events for Head!
[XSOVR] | 10/24/2022 6:33:38 AM | Device RightTracker subscribed to events for RightHand!
[XSOVR] | 10/24/2022 6:33:38 AM | Got Steamworks user icon!
[XSOVR] | 10/24/2022 6:33:38 AM | Tried to load Wrist Background at path a null or empty path!
[XSOVR] | 10/24/2022 6:33:38 AM | Starting Up SteamVR Connection...
[XSOVR] | 10/24/2022 6:33:39 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 1
<b>[SteamVR]</b> Initialized. Connected to lighthouse:LHR-7EBCA08C
[XSOVR] | 10/24/2022 6:33:39 AM | Loaded simulation mode bindings...
<b>[SteamVR]</b> Successfully loaded 27 actions from action manifest into SteamVR (C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets\SteamVR\actions.json)
[XSOVR] | 10/24/2022 6:33:39 AM | Connected to SteamVR!
[XSOVR] | 10/24/2022 6:33:39 AM | SteamVR Version: 1.24.6
[XSOVR] | 10/24/2022 6:33:39 AM | Current Tracking Universe: TrackingUniverseStanding
[XSOVR] | 10/24/2022 6:33:39 AM | Recentering Window Space.
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! XSOverlay_joystickui
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! XSOverlay_joystickuicursor
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! XSOverlay_startup
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! XSOverlay_wristoverlay
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! Raycaster.LeftTracker.VisualCursor
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! Raycaster.HMD.VisualCursor
[XSOVR] | 10/24/2022 6:33:39 AM | Overlay Created! Raycaster.RightTracker.VisualCursor
[XSOVR] | 10/24/2022 6:33:39 AM | HMD Polled String: index
[XSOVR] | 10/24/2022 6:33:39 AM | HMD Type: Index
[XSOVR] | 10/24/2022 6:33:39 AM | Attempting to load localization from file: C:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/en-US/ui.json
[DRP] Disposing Discord IPC Client...
[DRP] Finished Disconnecting
[XSOVR] | 10/24/2022 6:33:39 AM | <b>[XSOVR PLUGIN MANAGER]</b> Loaded keyboard sound pack: KeyboardSounds\Default
[XSOVR] | 10/24/2022 6:33:40 AM | Dashboard Event Open: True
[XSOVR] | 10/24/2022 6:33:42 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 2
[XSOVR] | 10/24/2022 6:33:42 AM | Dashboard Event Open: False
[XSOVR] | 10/24/2022 6:33:44 AM | Creating texture for Overlay: Tooltip_R
[XSOVR] | 10/24/2022 6:33:44 AM | Overlay Created! XSOverlay_tooltip_r
[XSOVR] | 10/24/2022 6:33:45 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 3
[XSOVR] | 10/24/2022 6:33:48 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 4
[XSOVR] | 10/24/2022 6:33:49 AM | Detected Headset Refresh Rate: 119
[XSOVR] | 10/24/2022 6:33:51 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 5
[XSOVR] | 10/24/2022 6:33:52 AM | Overlay Created! XSOverlay_toolbarglobal
[XSOVR] | 10/24/2022 6:33:52 AM | Overlay Created! XSOverlay_toolbarwindow
[XSOVR] | 10/24/2022 6:33:54 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 6
[XSOVR] | 10/24/2022 6:33:57 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 7
[XSOVR] | 10/24/2022 6:33:58 AM | Enabling Keyboard
[XSOVR] | 10/24/2022 6:33:58 AM | CheckKeyboardFormat() -> "United States - dvorak" -> ANSI Format
[XSOVR] | 10/24/2022 6:33:58 AM | Overlay Created! XSOverlay_keyboardoverlay
[XSOVR] | 10/24/2022 6:33:58 AM | Creating texture for Overlay: KeyboardOverlay
[XSOVR] | 10/24/2022 6:33:58 AM | Creating texture for Overlay: KeyboardOverlay
[XSOVR] | 10/24/2022 6:34:00 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 8
[XSOVR] | 10/24/2022 6:34:03 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Polling... Attempt 9
[XSOVR] | 10/24/2022 6:34:06 AM | RECEIVE_EVENT_MEDIA_PLAYER_UPDATE: 0 | Open Media Controls to Initialize
[XSOVR] | 10/24/2022 6:34:30 AM | Creating texture for Overlay: KeyboardOverlay
[XSOVR] | 10/24/2022 6:34:30 AM | Creating texture for Overlay: KeyboardOverlay
[XSOVR] | 10/24/2022 6:34:51 AM | Disabling Keyboard
[XSOVR] | 10/24/2022 6:35:02 AM | Dashboard Event Open: True
VR - QUIT - EVENT
[XSOVR] | 10/24/2022 6:35:05 AM | Saved config to: C:/Users/nat/AppData/LocalLow/Xiexe/XSOverlay/config
</details>

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment]
This should only be a problem in the SteamVR Grid / Home environment.
