### ISSUE TITLE
Windows reset almost every launch

### ISSUE THREAD

**Issue by imagitama** [Xiexe/XSOverlay-Issue-Tracker#234]
**Describe the bug in detail:**

Whenever I launch XSOverlay there is a chance that my windows (2 desktops) are reset - I have to recreate them.

**Provide steps to reproduce the bug:**

Create 2 windows - 1 for each desktop/monitor. Happy days. Then close SteamVR (and Virtual Desktop) and re-open them again. Usually the windows are destroyed and I have to re-create them.

1 desktop is a 4K monitor. The other desktop is a 2K vertical monitor.

**Expected behavior:**

It remembers my desktops. I don't have to manually do it.

**Output Log:**

Last log:

[output_log_2022-12-06__16.57.41.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10163577/output_log_2022-12-06__16.57.41.txt)

Couldn't find uWindowCapture or uDesktopCapture in install dir

**Additional Information:**

I mainly play VRChat

I have a Quest 2 with Virtual Desktop + OpenVR-SpaceCalibrator with Index controllers / Vive 3.0 trackers

**Comment by optimuspine82** [comment]
Same issue

**Comment by imagitama** [comment]
I talked to the devs and they said it is intentional.

Imo everything in software nowadays should auto-save by default. It's expected behavior coming from other software and clicking a button to save is extra effort.

**Comment by Xiexe** [comment]
Use the layouts feature to save layouts of windows that you would like to persist.

**Comment by optimuspine82** [comment]
It doesn’t save the windows that we’re assigned in the layouts. Those have to be set up each time.   
  
  
  
  
  
  
  

  
  
>
