### ISSUE TITLE
[Beta] Unable to switch between left hand and right hand mouse in 'Emulator Mouse' mode

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#243]
When using `Emulate Mouse` mode, you are unable to smoothly swap the mouse using your triggers between the left and right hand in your overlay. One of your pointers must always leave the overlay area in order for the mouse to swap to the other hand.

**Comment by Xiexe** [comment]
Fixed in next beta
