### ISSUE TITLE
[Beta] No tooltips on hover

### ISSUE THREAD

**Issue by JesperT-Indie21** [Xiexe/XSOverlay-Issue-Tracker#245]
When hovering over wrist icons there's no tooltip explaining what they mean.

I see the appeal in not having tooltips, but maybe there should be an option to disable tooltips instead of not having them.

**Comment by Swingly6061** [comment]
Oh boy, used the wrong account. xD

**Comment by Xiexe** [comment]
Tooltips will be added back before the beta ships to live. The tooltip handler in the client currently has no communication between the client and the Web UI clients.
