### ISSUE TITLE
make the desktop window unable to enter full screen

### ISSUE THREAD

**Issue by yui-123** [Xiexe/XSOverlay-Issue-Tracker#25]
**Describe the bug in detail:**
i was pushing buttons and accidentally got the window into full screen mode and even restarting hitting esc, f11 dont work you have to do alt + enter to fix it but i feel it could be quite possible for someone else to accidentally do that to and alt+enter inset a obvious fix for most people. so i think if its possible to just make the window not able to enter full screen it would be a good option as full screen is useless. im putting this in bug because i dont feel its really a feature request.

**Comment by Xiexe** [comment]
Ideally I will be able to hide the window entirely without causing issues. There's one problem in doing that in that it causes the cursor and UI stuff to update slowly. I will continue to experiment with it though.

**Comment by Yui-Hell** [comment]
can you make the window dock in the like thing in the botem right i dont know what its called would that work

**Comment by Xiexe** [comment]
Fixed in 465 as there is no longer a desktop window.
