### ISSUE TITLE
[SQU-277] Feature request: Only block inputs when cursor is on the overlay

### ISSUE THREAD

**Issue by Cedar-Winning** [Xiexe/XSOverlay-Issue-Tracker#250]
When you set it to block inputs, could there be an additional option to only do this when you are hovering over a window or the keyboard etc.
This feature would be much appreciated.

<sub>[SQU-277](https://linear.app/square-hole-interactive/issue/SQU-277/feature-request-only-block-inputs-when-cursor-is-on-the-overlay)</sub>

**Comment by Xiexe** [comment]
This is a good idea, I'll see what I can do. It may be a better method of input blocking in general.
