### ISSUE TITLE
Grey screens in VR

### ISSUE THREAD

**Issue by MrDj200** [Xiexe/XSOverlay-Issue-Tracker#252]
**Describe the bug in detail:**
So I've gotten a weird issue on the new Beta:
Every now and then (was not able to figure out what triggers it) I get a brown screen followed by a grey screen for about 5 seconds.
It only happens when XSO is actually running (tested over ~8 hours. Repeatedly turning XSO on for a while and then off)
At first I thought it was my VR cable/headset being broken, but as I said, it only happens when XSO is running.

**Provide steps to reproduce the bug:**
It seemed to be happening randomly. Was not able to reliable make it happen (other than waiting)

**Expected behavior:**
No greyscreen

**Output Log:**
[output_log_2023-02-11__22.08.49.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10715394/output_log_2023-02-11__22.08.49.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10715392/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10715393/uDesktopDuplication.log)
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

**Additional Information:**
HMD: Index
Other vr overlays: FPSVR & OVRAS

**Comment by MrDj200** [comment]
I forgot to mention that this is in the beta branch!
Sorry about that!

**Comment by MrDj200** [comment]
Update: Same thing happens in Stable branch. Which is weird, cause it never happened before.
But it still only happens when XSO is running. What troubleshooting steps could I try?

**Comment by Xiexe** [comment]
Try updating your motherboard bios. Otherwise, you may have some other issue that XSO is just allowing to be visible.

**Comment by MrDj200** [comment]
As it turns out, _something_ just changed the XSO notification scale to infinity and beyond, so the notification was just so enormous, it looked like a grey screen lol.
Not quite sure what caused it to flash white (and blind me in the process) though.

Forgot to close this ^^
