### ISSUE TITLE
Can't move overlays on Quest 2+Virtual Desktop

### ISSUE THREAD

**Issue by tuuz** [Xiexe/XSOverlay-Issue-Tracker#253]
**Describe the bug in detail:**
I can't move any overlays, including the settings window or keyboard. They are behaving as if they are locked. The only way I have found to move them is with loading a preset. Grid view button and recenter windows button also seem to work. Pushing buttons on the keyboard and interacting with the desktop also works.
**Provide steps to reproduce the bug:**
Steps to reproduce the behavior: Attempt to move any overlay in XSOverlay

**Expected behavior:**
The windows to move after I grabbed them.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

**Additional Information:**
I have tried restarting the app and Steam/SteamVR, reinstalling XSOverlay, resetting the settings to default in XSOverlay, making sure the binds were correct, and also tried rebinding grabbing to the top triggers and the A button, and running XSOverlay as an admin. None of these things helped.
The issue has existed since the fallback version was made available on the Steam betas. The fallback version still allows me to move windows/overlays.
I use a Quest 2 with Virtual Desktop.
[output_log_2023-02-14__04.01.56.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10731290/output_log_2023-02-14__04.01.56.txt)
[output_log_2023-02-14__04.06.38.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10731291/output_log_2023-02-14__04.06.38.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10731295/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10731296/uDesktopDuplication.log)

**Comment by Xiexe** [comment]
I’d also like to see your config file, it’s possible some sort of parsing is going wrong with the GrabSensitivity setting.

`C:/Users/%USERNAME%/AppData/LocalLow/Xiexe/XSOverlay/config/`

**Comment by tuuz** [comment]
The beta didn't seem to work either. I tried changing "GrabSensitivity" from 1.0 to 0.5 in the overlaySettings.json and that seems to have fixed it.
The uploaded file is before I made an edit to it. (I changed the extension to .txt from .json because Github wouldn't let me upload it as a .json)
[overlaySettings.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10738292/overlaySettings.txt)

**Comment by Xiexe** [comment]
Glad to hear changing that fixed it. I may start capping it at .75 or something so that people stop having it set to 1

**Comment by tuuz** [comment]
Found the setting in the beta version. Seems I can turn it all the way to 99% and have it still work. Just at 100% where it breaks.

**Comment by Xiexe** [comment]
Understood. Will cap to 99% in the next update.
