### ISSUE TITLE
Option to dynamically change contrast of wrist overlay text

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#254]
Right now the text for the wrist overlay displays as solid white. In some cases this is fine as is, but it starts to become an issue when listening to music for example and the background of the wrist overlay changes to an album cover of similar contrast. An option to dynamically adjust the text contrast in accordance to the backgrounds would be good to have to remedy this.

**Comment by Xiexe** [comment]
Text now changes to dark color if background is too light as of the latest beta

**Comment by SalbugVR** [comment]
This has helped in some cases, but looks there are still some issues in most though. For example, for certain album covers (Death Dynamic Shroud's "Heavy Black Heart" album to name one example) with a darker contrast background, the text will convert itself to a darker contrast as well, causing the initial issue but on the opposite end of the spectrum. Perhaps including a drop shadow or something of the like for the text will help here.
