### ISSUE TITLE
[Beta] OSC battery reports partially missing

### ISSUE THREAD

**Issue by lebaston100** [Xiexe/XSOverlay-Issue-Tracker#256]
**Describe the bug in detail:**
OSC only sends regular battery reports for one controller. Which one (left or right) is seemingly random, but could be down to power up order.
Before beta both (left and right) battery level was reported on a regular interval.

**Provide steps to reproduce the bug:**
- Setup an OSC receiver (i'm using node-red)
- Configure osc output port
- Power up controllers and startup steamvr
- Launch XSOverlay and wait for multiple minutes watching what data the osc receiver receives

**Expected behavior:**
Battery updates come in for left and right controller.

**Output Log:**
[output_log_2023-02-28__22.38.52.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/10860744/output_log_2023-02-28__22.38.52.txt)

**Additional Information:**
None

**Comment by Xiexe** [comment]
Noted!

**Comment by lebaston100** [comment]
Pleased to report this seems to be fixed with one of the latest beta versions.
