### ISSUE TITLE
Wrist menu appears in floor

### ISSUE THREAD

**Issue by imagitama** [Xiexe/XSOverlay-Issue-Tracker#259]
**Describe the bug in detail:**

The wrist menu sometimes appears into the floor (out of reach) and does not move with my hand controller. The same with the keyboard. Desktop overlays are sometimes way off in the distance.

**Provide steps to reproduce the bug:**

It is random. Sometimes it happens, sometimes it doesn't.

**Expected behavior:**

When I open my overlays (double pressing A button) and rotate my wrist, the wrist menu appears.

**Output Log:**

[output_log_2023-04-04__21.28.18.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/11149096/output_log_2023-04-04__21.28.18.txt)

**Additional Information:**

Using Quest 2 with OpenVR Space Calibrator with Index controllers and Vive 3.0 trackers.

**Comment by Xiexe** [comment]
This should be fixed.
