### ISSUE TITLE
[226] Vertical window not working

### ISSUE THREAD

**Issue by PhaxeNor** [Xiexe/XSOverlay-Issue-Tracker#26]
**Describe the bug in detail:**
When switching to a monitor that is vertical, the window is stuck on horizontal view.

**Provide steps to reproduce the bug:**
- Add Window
- Switch to Vertical Window

**Expected behavior:**
Window rotate to be vertical.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4253443/output_log.txt)

**Additional Information:**
![image](https://user-images.githubusercontent.com/323222/75312572-a2367400-585a-11ea-8ccc-5f3c4fe05e9f.png)

**Comment by PhaxeNor** [comment]
Picture was a bit weird, but the window settings is just below at the bottom

**Comment by Xiexe** [comment]
Fixed in next patch!
