### ISSUE TITLE
Input locking icon does not show when clicking on a locked window

### ISSUE THREAD

**Issue by ScruffyRules** [Xiexe/XSOverlay-Issue-Tracker#27]
**Describe the bug in detail:**
Clicking on a input locked window does not show the lock icon

**Provide steps to reproduce the bug:**
Enable Input Locking on a window
Try and click on it

**Expected behavior:**
An icon will appear when trying to click on a input locked window

**Output Log:**
N/A

**Additional Information:**
N/A

**Comment by Xiexe** [comment]
Not doable anymore due to changes in how the windows are rendered - will come up with a replacement solution in the future.
