### ISSUE TITLE
Input locking does not stop windows cursor movement and scrolling

### ISSUE THREAD

**Issue by ScruffyRules** [Xiexe/XSOverlay-Issue-Tracker#28]
**Describe the bug in detail:**
While a window is input locked, the windows cursor still follows the overlay's cursor, you can also still scroll while input locking is enabled.
This also still focuses the window

**Provide steps to reproduce the bug:**
Enable input locking on a window
Hover overlay cursor
See Windows cursor movement

**Expected behavior:**
Windows cursor not moved
Window is not focused
Scrolling can not be done

**Output Log:**
N/A

**Additional Information:**
Input locking should be called Input blocking.

**Comment by Xiexe** [comment]
Fixed in next build
