### ISSUE TITLE
Curved Overlay Becoming Unresponsive

### ISSUE THREAD

**Issue by SpiritsCreations** [Xiexe/XSOverlay-Issue-Tracker#280]
**Describe the bug in detail:**
When having Curved Overlays Enabled and Creating a Window, upon moving the Overlay after a period of time the overlay becomes unresponsive, and upon any new creation of a Window the same result happens!
(Issue is between Non-Beta & Beta)

**Provide steps to reproduce the bug:**
Curved Overlay Enabled
Spawn a Window
Move Overlay around multiple times
Then Overlay becomes unresponsive with no User Input

**Expected behavior:**
Spawn a Window with Curved Overlay enabled and being able to fully use the Overlay during the Period of time within VR without having to close the window

**Output Log:**
[output_log_2023-09-26__08.06.49.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/12747623/output_log_2023-09-26__08.06.49.txt)
[output_log_2023-09-28__01.40.44.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/12747627/output_log_2023-09-28__01.40.44.txt)
[output_log_2023-09-28__03.08.14.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/12747628/output_log_2023-09-28__03.08.14.txt)

**Additional Information:**
Windows 11 Pro 22H2
SteamVR Beta 2.0.2
Steam (Non-Beta & Beta)
Current Fix Disabling Curved Overlays!

**Comment by Xiexe** [comment]
Tracked down to an issue with the steamvr beta and should have been fixed or will be fixed soon on valves side.
