### ISSUE TITLE
[BETA] [Build 617] Wrist overlay doesn't transfer with you when switching pairs of controllers.

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#287]
When swapping controllers or pairs of controllers, the wrist overlay doesn't transfer over to the other pair from the original controllers used when the overlay was initialised.

**Comment by LoliGoddess** [comment]
can confirm this happens to me to

**Comment by Xiexe** [comment]
Cannot reproduce. Turning off my controllers and switching to a new set works fine for me on RC4

**Comment by Xiexe** [comment]
nvm. figured out a way to get it to happen, fixed.
