### ISSUE TITLE
[BETA] Wrist Overlay opacity resets to 100% on restart

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#289]
When restarting XSOverlay, the opacity resets to 100% even though in the settings it's still what you set it to. It's fixed by just nudging the slider again. In my case, it fixes when I nudge the slider back and forth and look away from the overlay for it to disappear then back when it reappears when it's back in my viewing angle.

Repro Steps:

1. Set wrist opacity to a noticeably low number

2. Restart XSOverlay

3. Observe how the wrist overlay is opaque again

4. If you have the wrist viewing angle set and turned on, adjust the opacity slider again and twist your wrist out of the set viewing angle and back again, overlay should be back at set transparency

**Comment by Xiexe** [comment]
Fixed
