### ISSUE TITLE
[BETA] [Build 624] Media Player theming tweaks affects wrist overlay colours despite being closed

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#290]
> - Slight Wrist themeing tweaks when media player is open

Even with Smart Media Player turned off and the media player collapsed, the colour theming for the wrist overlay will change colours to match any media playing. Fixed by opening and closing the wrist player.

**Comment by Xiexe** [comment]
fixed
