### ISSUE TITLE
[625] Emulate Mouse option causes 1-second freezes after each click.

### ISSUE THREAD

**Issue by BluWizard10** [Xiexe/XSOverlay-Issue-Tracker#293]
**Describe the bug in detail:**
For some weird reason, using Emulate Mouse instead of Touch Control causes the Overlay Windows to completely freeze the Mouse's movement for 1 second until it moves to the cursor again.

**Provide steps to reproduce the bug:**
1. Set to Emulate Mouse. Do not use Touch Control.
2. Try casually using the Overlay as per usual.

**Expected behavior:**
I expected the Mouse to continuously follow the Cursor as per usual, just like from previous versions.

**Comment by Xiexe** [comment]
Closing this as it was determined to be a user setting issue!
