### ISSUE TITLE
[BETA] [Build 265] Controllers Batteries stuck at 100%

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#294]
On Build 265, the battery levels for peripheral devices is stuck at 100%. Even after restarting my PC, it's still stuck at 100%.

![vrmonitor_Xc0qLygxH8](https://github.com/Xiexe/XSOverlay-Issue-Tracker/assets/24326270/710211b3-8911-402e-888b-d61970819f40)
![vrmonitor_ZYI6VotiaA](https://github.com/Xiexe/XSOverlay-Issue-Tracker/assets/24326270/7168ed67-698c-4bf0-a13e-883721ee1a04)

**Comment by Xiexe** [comment]
Fixed
