### ISSUE TITLE
[625] Turning on Tundra Trackers fires a false-positive Low Battery Notification

### ISSUE THREAD

**Issue by BluWizard10** [Xiexe/XSOverlay-Issue-Tracker#296]
**Describe the bug in detail:**
Tundra Trackers have a long-standing issue where the Battery Percentage will read as 0% when powered on for up to a minute until the actual percentage is given. This causes XSOverlay to falsely assume the Tracker is on Low Battery and fires the notification.

In previous versions of XSOverlay, this never happens.

**Provide steps to reproduce the bug:**
- Simply power on a Tundra Tracker while XSOverlay is active.

**Expected behavior:**
It should never fire a Low Battery Alert until the actual percentage is being read.

**Additional Information:**
Many people using Tundra Trackers (I know there are a LOT, just as much as Vive users) will see this as extremely annoying and will cause confusion. So much so that it would convince the user to use a different Overlay instead of XSO. I don't think you want that. Nobody would ever want to disable Low Battery Alerts on an Overlay, ever.

**Comment by Xiexe** [comment]
Fixed for release
