### ISSUE TITLE
[SQU-318] Please add option to increase ui size

### ISSUE THREAD

**Issue by JusticeGoat** [Xiexe/XSOverlay-Issue-Tracker#301]
I can't see battery percentage on the new ui i have bad eyes.

<sub>[SQU-318](https://linear.app/square-hole-interactive/issue/SQU-318/please-add-option-to-increase-ui-size)</sub>

**Comment by Xiexe** [comment]
Added in 629.

https://store.steampowered.com/news/app/1173510/view/3731854112026877505
