### ISSUE TITLE
Update node to LTS supported version

### ISSUE THREAD

**Issue by euan142** [Xiexe/XSOverlay-Issue-Tracker#302]
**Feature Description:**
Noticed when this latest update came out an odd prompt for node requesting networking access, dug deeper and found node is now bundled with XSO. From what I can tell it's v16.15.1 which was support for was ended in September (it seems it was moved sooner for security reasons), v18 is now the LTS.

**Comment by Xiexe** [comment]
Reeee. But okay.

I'll update it soon. Annoying that the LTS was changed as soon as I patched basically.
