### ISSUE TITLE
Media Theme is being applied when it shouldn't

### ISSUE THREAD

**Issue by DrBlackRat** [Xiexe/XSOverlay-Issue-Tracker#309]
**Issue:**
The Media Theme is always being applied when media starts playing or is playing on launch when Smart Media Controls are disabled.
This can be fixed temporarily by opening and closing the media controls, but it will return once "something" about the media changes (play / pause, new media, etc)

**Expected Behaviour:**
The Media Theme should only be applied if the Media Controls are open and should respect when the user has Smart Media Controls disabled.

**Attachments:**
Here is a picture showcasing the issue:
![image](https://github.com/Xiexe/XSOverlay-Issue-Tracker/assets/46327609/94ac5502-14df-4f18-9e7f-ac10aed467da)

Here is my output log:
[output_log_2023-10-22__21.55.18.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/13078232/output_log_2023-10-22__21.55.18.txt)

**Comment by Xiexe** [comment]
Fixed in 632
