### ISSUE TITLE
[228] Vertical monitor is sideways until capture reset button clicked

### ISSUE THREAD

**Issue by lyuma** [Xiexe/XSOverlay-Issue-Tracker#31]
**Describe the bug in detail:**
I have a vertical monitor. While the movement bugs were fixed, when I open a new window, it shows sideways as long as I do not select a specific window. If I click the middle button at the bottom to reset input capture, the window flickers and next time I grab it turns the correct direction.

issue 26 also covers this or a similar issue from the previous build (226), but I wish to file a separate bug because the behavior is different on the latest build (228).

**Provide steps to reproduce the bug:**
1. Set monitor rotated.
2. Start XSOverlay
3. Create a window
4. Try dragging the window around etc. It remains sideways (mouse movement is 90 degrees off)
5. Click the middle button on the bottom.
6. Window is correctly rotated.

**Expected behavior:**
Vertical displays should be vertical always, and no flickering to horizontal.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4261809/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4261810/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4261811/uDesktopDuplication.log)

**Additional Information:**
None

**Comment by Xiexe** [comment]
i cant recreate this locally. what build are you on?

**Comment by Xiexe** [comment]
Fixed primary monitor being rotated incorrectly initially if in portrait or portrait flipped.
