### ISSUE TITLE
XS crashes at low battery percentage warning value

### ISSUE THREAD

**Issue by CaelBun** [Xiexe/XSOverlay-Issue-Tracker#319]
**Describe the bug in detail:**
XS crashes at low battery percentage warning value.

**Provide steps to reproduce the bug:**
controller needs to be at or lower than the battery warning.

**Expected behavior:**
XS notifies you when the battery reaches at specific value.

**Output Log:**
[output_log_2024-01-30__21.26.51.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/14106023/output_log_2024-01-30__21.26.51.txt)
[output_log_2024-01-31__02.16.26.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/14106024/output_log_2024-01-31__02.16.26.txt)
[output_log_2024-01-30__23.44.01.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/14106025/output_log_2024-01-30__23.44.01.txt)

**Comment by CaelBun** [comment]
beta version

**Comment by Hackebein** [comment]
I haven't tested it yet but this sounds like my issue when XSOverlay crashes after many hours in VR and can't get started anymore

**Comment by Xiexe** [comment]
This should now be fixed on beta 664
