### ISSUE TITLE
HighContrast mode breaks options menu // no  --disable-features=ForcedColors flag to help disable

### ISSUE THREAD

**Issue by PoptartGhost** [Xiexe/XSOverlay-Issue-Tracker#320]
**Describe the bug**
its not exactly a bug , at least not the request for a flag for --disable-features=ForcedColors  to work, but it seems with HC mode enabled I cannot properly see the left side of the  right side of the options menu. Also all the sliders look very messed up from my HC mode lol. that could be fixed but mostly it would be great just to be able to disable this as HC mode takes away all the beautifiul design that xs has become.

**To Reproduce**
1. Go to 'windows high contrast mode'
2. enable system wide
3. launch vr  +xs overlay
4.  open options menu and try and see check boxes on the left hand side (the text size seems diffrent too, but I cant find any system settings thats changed to do this incl my font size)

**Expected behavior**
--disable-features=ForcedColors in a shortcut target line, flag the program to ignore HC mode/system themes 

**Screenshots**
![image](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/assets/49379196/178a4f29-033c-42f4-b440-7e74cc4e182d)

**Software (please complete the following information):**
 - OS:  win 10
- newest xs overlay 

**Additional context**
Ive tried adding --disable-features=ForcedColors to shortcuts, the url of the steam shortcut in the start menu , and even launching it this way with powershell; but to no avail.

**Comment by Xiexe** [comment]
what the hell lmao

alright ill try and figure this out

**Comment by PoptartGhost** [comment]
yeah sorry im such a weirdo and use wild settings. 
in most programs its said that if you do the --disable setting it will just exclude it but not all.  It would mean alot if this would be compatable and ur super based for trying <3 thank you thank you

**Comment by PoptartGhost** [comment]
and to further explain its probably not ENTIRELY a problem with HC mode.  The text and sizing sure, but the black on black is probably from my specific settings.  instead of fixing HC mode id honestly suggest just adding exlusion ability if you can.
![image](https://github.com/Xiexe/XSOverlay-Issue-Tracker/assets/49379196/f00f005f-f579-4507-8f36-147a14e28151)
 (my discord for referance of how fucked up my theme is , no css)

**Comment by PoptartGhost** [comment]
![image](https://github.com/Xiexe/XSOverlay-Issue-Tracker/assets/49379196/a9f33ffc-5011-4e37-a371-97c728803c89)
adding this referance for testing. i dont think this is whats breaking XS entirely, but it could help for some missing font or check boxes. the size issue and the missing sliders is something else. 

Jsyk aswell discord has a mix of working and not working sliders  in HC mode. i just disable hc on it using that setting. i think most people would be happy with that rather than fixing to work with hc

**Comment by Xiexe** [comment]
will be fixed in next beta release
