### ISSUE TITLE
Overlay refuses to open

### ISSUE THREAD

**Issue by ApolloGarvan** [Xiexe/XSOverlay-Issue-Tracker#329]
**Describe the bug in detail:**
The program has to manually be opened. When or if it opens, doesn't fully load, and immediately closes.

**Provide steps to reproduce the bug:**
Steps to reproduce the behavior: Trying to open the program while in SteamVR.

**Expected behavior:**
What do you expect to happen, rather than what does happen?

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.
[output_log_2024-06-06__02.18.22.txt](https://github.com/user-attachments/files/15744206/output_log_2024-06-06__02.18.22.txt)
[output_log_2024-06-06__14.42.22.txt](https://github.com/user-attachments/files/15744207/output_log_2024-06-06__14.42.22.txt)
[output_log_2024-06-06__19.06.40.txt](https://github.com/user-attachments/files/15744208/output_log_2024-06-06__19.06.40.txt)

**Additional Information:**
Provide any additional information here.

**Comment by hazre** [comment]
might be related to #322, check my comment there and see if that works for you.

**Comment by ApolloGarvan** [comment]
That was what I had tried to begin with, and it still didn't fix. I thought I had typed that in, my mistake.

**Comment by ApolloGarvan** [comment]
> might be related to #322, check my comment there and see if that works for you.

tried it again, I must have missed a step, as iit seems to work now.
