### ISSUE TITLE
Disabling "enabled curved overlays" option does not disable curved overlays

### ISSUE THREAD

**Issue by Phasedragon** [Xiexe/XSOverlay-Issue-Tracker#36]
All it does is prevent you from modifying how curved an overlay is, rather than forcing them flat.

If a window is in this state where it's still curved but you can't change how curved, then this also locks it to be horizontal, and it cannot be pitched up or down.

**Comment by Xiexe** [comment]
Will be fixed in the next build, along with scaling ignoring the curvature option.
