### ISSUE TITLE
Curved overlays get weird when you recenter outside the smart roll angle

### ISSUE THREAD

**Issue by Phasedragon** [Xiexe/XSOverlay-Issue-Tracker#38]
They seem to curve on multiple axes or something 

before: https://imgur.com/FmmtYRM 

after: https://imgur.com/kdcwi0j

**Comment by Xiexe** [comment]
This is a bug with Valve's curvature projection, and I can't really do much about it. I reported it to them, they didn't seem to care. 

It'll be fixed in that I will prevent curvature on overlays if the smart roll kicks in.
