### ISSUE TITLE
left click bind dose not work on keyboard

### ISSUE THREAD

**Issue by Yui-Hell** [Xiexe/XSOverlay-Issue-Tracker#39]
i tried using the dedicated left click key bind sinse i use a as left click and it doesn't register on the keyboard

**Comment by Xiexe** [comment]
It's a left click, not a UI click :P

**Comment by Yui-Hell** [comment]
lol true

**Comment by Yui-Hell** [comment]
its just not obvious i guess that trigger depth is the bind you need to set to change you left click

**Comment by Xiexe** [comment]
The Left Click binding serves it's purpose though, trigger depth is used for more than just clicking. UI click and desktop clicking are their own systems.

**Comment by Yui-Hell** [comment]
true it confused me at first
