### ISSUE TITLE
[176] Unable to delete window

### ISSUE THREAD

**Issue by PhaxeNor** [Xiexe/XSOverlay-Issue-Tracker#4]
**Describe the bug in detail:**
Unable to delete the selected window.

**Provide steps to reproduce the bug:**
Open new window
Go to settings
Click Delete

**Expected behavior:**
That the window would be removed.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4178892/output_log.txt)

**Additional Information:**
Window still updates, but can't interact with it. Adding a new windows allows you to interact with the old one again.

https://cdn.discordapp.com/attachments/628376970203496448/676277246066950144/2020-02-10_05-02-50-1.mp4

**Comment by Xiexe** [comment]
fixed in 177
