### ISSUE TITLE
Blue Dot at Playspace Origin

### ISSUE THREAD

**Issue by MMMaellon** [Xiexe/XSOverlay-Issue-Tracker#40]
A copy of the blue dot that is used as the cursor shows up on the floor at my playspace origin. It's always there even when my windows are closed or if both of my cursors are visible.

Steps to reproduce the behavior: It happens every time I boot up XSOverlay

**Expected behavior:**
There should be no blue dot.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4283083/uDesktopDuplication.log)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4283084/uWindowCapture.log)

**Comment by Xiexe** [comment]
Will fix in next build. Thank you!
