### ISSUE TITLE
Numberpad support

### ISSUE THREAD

**Issue by Sarniwoop** [Xiexe/XSOverlay-Issue-Tracker#41]
**Feature Description:**
Add the numeric keypad to XSOverlay, including the num lock button.

**Comment by hakanai** [comment]
Ooh, a slide-out numberpad? Can it also have an integrated calculator?

**Comment by orels1** [comment]
@Xiexe this can be closed I guess?

**Comment by Xiexe** [comment]
Indeed it can, missed this. Woops.
