### ISSUE TITLE
Wrist overlay and toolbar bug with The Walking Dead: Saints & Sinners

### ISSUE THREAD

**Issue by GigabitsGame** [Xiexe/XSOverlay-Issue-Tracker#43]
Describe the bug in detail: 

The wrist overlay/toolbar is moved ver far from the user and cannot be used while the game is active. 

Start XSOverlay, then play The Walking Dead: Saints & Sinners. When the games loads the wrist overlay and toolbar are moved far from the user and cannot be used. As soon as you exit the game, the overlay and toolbar go back to their normal spots.

Expected behavior: 

Wrist overlay is supposed to remain on the wrist and toolbar be accessible while the game is active.

Output Logs:
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4284379/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4284380/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4284381/uDesktopDuplication.log)

**Comment by Xiexe** [comment]
Does this game force you into a seated play environment? If so I'll need to look into fixing that ASAP.

**Comment by Xiexe** [comment]
Should be fixed in build 267!
