### ISSUE TITLE
option to disable auto rotate on a window

### ISSUE THREAD

**Issue by Murkur** [Xiexe/XSOverlay-Issue-Tracker#45]
option to disable the auto rotation and alignment when moving windows.

kinda annoying when you want to move a window a small bit and now its completely miss aligned or when you look directly up and you cant easily view the window

**Comment by Xiexe** [comment]
Sorry, but this probably isn't something I'm going to do, as supporting two different movement systems would be taxing to test with! I'll look into improving the behavior of the current system, though.

**Comment by Murkur** [comment]
awe damn that sucks the auto rotation is really annoying why laying down
