### ISSUE TITLE
Curved Monitor bug

### ISSUE THREAD

**Issue by Hordini** [Xiexe/XSOverlay-Issue-Tracker#46]
**Describe the bug in detail:**
When Curved Monitor is enabled in Window Settings, and you have a flat window on your hand, the collision with the dot cursor acts like it's on a curved display.

**Expected behavior:**
I would expect for the dot cursor to stay on the flat plan instead of acting like it's on a curved one.

**Comment by Xiexe** [comment]
Hi! This is just an issue with how were resetting the curved state when a window gets attached. Grabbing and dropping the window should fix the collision for now. I'll hopefully get a fix in for this next patch though!

**Comment by Xiexe** [comment]
Fixed in next patch
