### ISSUE TITLE
Phone display?

### ISSUE THREAD

**Issue by Nepsyneptune** [Xiexe/XSOverlay-Issue-Tracker#47]
Would be cool as heck to have a app /cast my phone display and interact with it on Xs overlay owo 

Doubt would be doable anytime soon 
But would be nice to answer texts or use phone apps on the overlay owo.

**Comment by Phasedragon** [comment]
I looked into the options available for this. Interestingly, windows 10 actually has a built in feature to turn your desktop into a cast-able display. It's called the connect app, and once it's open it shows up in your phone like a chromecast or smart tv. It's only one-way though, so you have to go to third party apps to transfer input from the desktop to the phone. One app I've tried, APowerMirror, seems to do a decent job. https://www.apowersoft.com/phone-mirror. Over wifi, it only does display. But over USB, it's able to do input as well. It doesn't do audio however, so you might want to keep looking. But either way, it's not exactly a feature that XS would have anything to do with.

**Comment by Xiexe** [comment]
Probably not going to be added, will be something users can eventually do with plugin support when we get to that stage.
