### ISSUE TITLE
Cursor smoothing for motion controllers

### ISSUE THREAD

**Issue by Phasedragon** [Xiexe/XSOverlay-Issue-Tracker#50]
I'm not a huge fan of the way OVRTK does it because it feels like it's just interpolating and simply lowering the sensitivity. But after trying oculus dashboard's implementation, I was convinced that it is possible to do this well. The way they do it is to have a sort of dead zone around the cursor so if you stay within a very tiny circle, it doesn't move at all. This seems like the kind of thing that XS could excel at given it's target features.

**Comment by Xiexe** [comment]
Actually, I originally had something like this. That is exactly how my original smoothing worked. 

I ended up scrapping it because it just didn't feel good at the time. 

Things have changed though, so I may end up trying reimplementing it.

**Comment by Xiexe** [comment]
Added in a previous build.
