### ISSUE TITLE
Captured Browser Windows are displayed transparent

### ISSUE THREAD

**Issue by susch19** [Xiexe/XSOverlay-Issue-Tracker#51]
When i capture any browser application (Tested with Chrome, Opera, Edge and even Steam) it doesn't show the content, but only the border and the rest is transparent.
It works however, when capturing the complete screen, then the content is displayed as expected.

**Provide steps to reproduce the bug:**
Capture a browser only window in XSOverlay 

**Expected behavior:**
Window is displayed like any other window.  

**Output Log:**
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
Only error in output log is "VROverlayError_InvalidHandle". 
Thats most likely the main reason it's not working.

uWindowCapture: [uWC::Err][2020-03-20 18:39:36] WindowManager::GetWindow => Window whose id is 57 does not exist.
uDesktopCapure: No Errors

**Additional Information:**
Tried it with the latest version on steam (267 according to the Activity log). 
I already tried restarting everything, including my pc.

**Comment by Xiexe** [comment]
That's.. interesting. I'll see if I can recreate it locally later tomorrow when I'm working again!

**Comment by susch19** [comment]
If you cant recreate it, i can offer my help. I'm a c# developer myself, even though i normaly try to avoid unity, because of many reasons. 
Sadly dnspy debugging only works with debug builds. Maybe its something wierd happening with uWindowCaptureand the fact,. that i'm on the insider preview from microsoft. They already broke fusion360 at one time, so i wouldn't be that suprised

**Comment by susch19** [comment]
So i did a bit more testing today.

**Beta Branch**
Was a whole lot worse. Could only capture telegram window and SteamVr. 
Tested: Firefox, Chrome, Opera, Thunderbird, VS, VS Code, Notepad, Notepad++, Task-Manager, OBS and Teamspeak
I've tried running from steam and as admin by starting the exe, but same result both times.

**"Stable" Branch**
I started XSOverlay with admin priviliges and could capture:
Opera, Teamspeak, OBS, Telegram, VS and Google Play Music Desktop Player

*No Capture possible*
Firefox, Chrome, VS Code, a simple WPF Application

*Capture with Bugs*
Notepad, Windows Explorer and Geforce Experience had a transparent background (Maybe Dark Theme Problem?)
Task-Manager graphs were fine, but everything else was transparent.

Errors were the same as in the original post

**Comment by Xiexe** [comment]
I haven't changed anything with the window captures or fixed the handle error on beta. All I added was the first iteration of layout saving and fixed some minor bugs.

The Handle error is something valve changed and neglected to document, so I'll have to look further than I'd like to fix. I doubt it's causing your issues though.

What are your system specs? Are you on a hybrid system? 

I'm able to correctly capture all windows, regardless of the invalid handle error.

**Comment by susch19** [comment]
What do you mean with a hybrid system?
Specs are:
Ryzen 7 2700x
Rtx 2080
48gb Ram

Htc Vive, Index Controller, newest Steam Vr Version
Windows 10 Pro Insider Preview Build 19577.rs_prerelease:200228-1439

Than it's even weirder that it has other results. Do you have any idea what i could test, which may help you resolving this issue?

**Comment by Xiexe** [comment]
Hybrid system would be something like a laptop that runs off of both the integrated and dedicated GPU using Nvidia Optimus. Those specs sound like it wouldn't be the case though.

I'm not sure what to test from here, it might be an insider build thing, or a driver issue. 

I'd try updating or downgrading GPU drivers, and if all else fails, if you're capable of it, testing on a machine that's not on a windows 10 insider build.

**Comment by susch19** [comment]
Ohh that's what you meant. Nah normal tower pc.

GPU Driver was updated today and windows wants an update as well. Maybe i will try up and downgrading my windows installation to see, how persistent this issue is. As soon as ive done this, i will inform you about my findings.

**Comment by susch19** [comment]
I have some news. So downgrading to latest preview and upgrading to newest didn't help. Downgrading to latest stable isn't possible.
So i decided to test uWindowCapture without XSOverlay and it's exactly the same. So it's not your code that's causing this issue. But it's still weird, that in the beta branch it's even worse which doesn't make sense at all.

I will open an issue in the repo of hecomi, maybe he has a solution for this problem

**Comment by susch19** [comment]
If someone else has this issue, disabling hardware accelaration in the browser you want to capture, is a workaround. 

I maybe look into this issue with a friend of mine and implement the Windows Graphics Capture (It's used by obs for example). Than you could have a setting to switch between different modes.
Sadly Windows Graphics Capture only works for Win 10 1903 and up, but as a optional feature that wouldn't matter i guess and this application is already win 10 only.

**Comment by Xiexe** [comment]
Implementing and replacing UWC with the UGC API is something I plan to do, but it won't be happening soon as I've got a few other things that I need to get done first. 

It's interesting that disabling hardware accel helps, since as far as I'm aware most people don't need to do that.

**Comment by Xiexe** [comment]
Going to close this issue for now until more information arises!
