### ISSUE TITLE
Provide german keyboad layout

### ISSUE THREAD

**Issue by susch19** [Xiexe/XSOverlay-Issue-Tracker#52]
**Feature Description:**
Currently only a few keyboard layouts are supported and that wouldn't be an issue, if the special keys wouldn't map differently.
For example the Key '\' on the english keyboard results in a '#' on a german pc. 

Alternatively if the pressed keys are mapped correctly, so a '\' would show as a '\' in all languages, that would be fine too.

**Comment by Xiexe** [comment]
Hi! Keyboard layouts can be made by launching with the -KeyboardEditor or -keyboardeditor launch parameter. (either should work)

As for a German layout, I believe someone has already made one. If you're in the community discord, you can download them from the #keyboard-layouts channel. If not, in the future, I plan to add workshop integration to make things more streamlined. That may be awhile away though.

Downloaded keyboard layouts can be added through (InstallDirectory)/XSOverlay_Data/StreamingAssets/Plugins/KeyboardLayout/(layoutname.json)

You can then load them by hitting the settings gear on the keyboard and choosing it from the list of loaded layouts there!

**Comment by susch19** [comment]
Oh wow thanks, that's easy. I would recommend making a small help note or button in the keyboard layout seetings or maybe i just didn't see it
