### ISSUE TITLE
Keyboard shortcuts to switch layout, recenter, enter/exit edit mode.

### ISSUE THREAD

**Issue by Phasedragon** [Xiexe/XSOverlay-Issue-Tracker#54]
It would be really nice to be able to launch and use XS in a limited state entirely without using controllers. Layouts make that possible, just missing the keyboard shortcuts to make it happen.

**Comment by Xiexe** [comment]
High priority to get finished before the end of next beta.

**Comment by Xiexe** [comment]
Added Simulation mode in beta 288
