### ISSUE TITLE
Minimal display toggle stuck on minimal mode after restart

### ISSUE THREAD

**Issue by PhaxeNor** [Xiexe/XSOverlay-Issue-Tracker#56]
**Describe the bug in detail:**
When enabling the minimal display, the state of it will be stuck in that every time you restart the application. You can toggle between, but it's reset to minimal when you start it again

**Provide steps to reproduce the bug:**
- Enable minimal display
- Re-enable the large display
- Restart XSOverlay
- Wrist display will now start it minimal mode 

**Expected behavior:**
Start in the toggled display state which would be the large one in this case.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4400561/output_log.txt)

**Additional Information:**
Beta version

**Comment by Xiexe** [comment]
Fixed in next beta build
