### ISSUE TITLE
System keyboard layout.

### ISSUE THREAD

**Issue by GenesisAria** [Xiexe/XSOverlay-Issue-Tracker#57]
**Feature Description:**
Use active OS keyboard layout as a premade or default option.  Oculus dash and some games do this to correct for custom or language layouts.

This would save a lot of effort for those needing unique keyboard layouts or language-specific.

**Comment by Xiexe** [comment]
This would require us to make a keyboard layout json for each language we wanted to support, which, unfortunately, given that we are a team of two, one of which is much more busy than the other, it doesn't really make sense time wise for us to focus on. 

In the future, we've talked about adding workshop support for keyboard layouts and sound packs and such.

**Comment by GenesisAria** [comment]
that is not what i meant, you can fetch the exact layout from registry pretty sure.  The games that do this fetch your actual inputs, not what language you are using. For instance i manually remap my capslock to backspace and the games, as well as oculus dash recognise it.

**Comment by Xiexe** [comment]
Ah, okay, thanks for clarifying. I'll look into this more!

**Comment by Xiexe** [comment]
Added since Beta 535
