### ISSUE TITLE
Option for triggers to use touch style input

### ISSUE THREAD

**Issue by GenesisAria** [Xiexe/XSOverlay-Issue-Tracker#58]
**Feature Description:**
Touch input displays indicators for click, double click, hold for right click etc. It also allows for grabbing and dragging in place of scrolling.

I have a feeling it may be far more complicated/difficult than i anticipate, but i figure it's worth suggesting.

**Comment by ubergeek77** [comment]
Hey there @Xiexe , I just bought XSOverlay today and I was wondering about this feature.

Have there been any developments on this feature since your last comment?

**Comment by Xiexe** [comment]
added in the latest betas
