### ISSUE TITLE
Multi Monitor issues

### ISSUE THREAD

**Issue by LewisSnow** [Xiexe/XSOverlay-Issue-Tracker#59]
So it would appear that the overlay sometimes doesn't want to capture multiple monitors as well as it wont take any inputs for any other monitor then the main one. 
(Issues capturing other monitors that are not the main one/ Interacting with other monitors doesn't work)

Can not find a way to reproduce, It seems this is a constant issue even after restarts.

Logs.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4432696/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4432698/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4432699/uDesktopDuplication.log)

**Comment by Xiexe** [comment]
Sorry for taking awhile to get to this - from the logs, it seems like you're running a system with monitors plugged into both the integrated graphics chip and your actual GPU. 

We currently don't support this if that is the case - and are working on a new capture API that *might* solve that problem, but we don't have an eta currently on when that will be released.

**Comment by Xiexe** [comment]
I've implemented a fix in the upcoming beta 304 build, mouse input should now work correctly on monitors captured that are not on the main GPU.
