### ISSUE TITLE
[177] XSOverlay crash when exiting SteamVR

### ISSUE THREAD

**Issue by PhaxeNor** [Xiexe/XSOverlay-Issue-Tracker#6]
**Describe the bug in detail:**
When you exit SteamVR without closing the overlay, the overlay will crash and exit.

**Provide steps to reproduce the bug:**
Start SteamVR
Start XSOverlay/Wait for it to start
Close SteamVR
XSOverlay crash

**Expected behavior:**
XSOverlay exit cleanly without any crash window.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4183238/output_log.txt)

**Additional Information:**
Tested on both SteamVR 1.9.16 and SteamVR Beta 1.10.12, same result on both.

**Comment by Xiexe** [comment]
Will fix.

**Comment by Xiexe** [comment]
Fixed in 180
