### ISSUE TITLE
CPU, RAM, GPU Usage bars

### ISSUE THREAD

**Issue by LewisSnow** [Xiexe/XSOverlay-Issue-Tracker#60]
Much like OVRtoolkit's display of showing the Usages really, Its nice to be able to quickly look down and check them. 

![image](https://user-images.githubusercontent.com/61498631/78463470-0b57a580-76ab-11ea-9741-edb4016cb042.png)

**Comment by Xiexe** [comment]
Added to the ToDo list

**Comment by Xiexe** [comment]
Added in build 465.
