### ISSUE TITLE
The Ability to Quit Xsoverlay from the Interface

### ISSUE THREAD

**Issue by owlboy** [Xiexe/XSOverlay-Issue-Tracker#62]
**Feature Description:**
I jumped into Half-life: Alyx last week and realized quickly I wanted to quit XSOverlay. But could not figure out how to do it from the XSO interface.

**Additional context:**
Did I just miss it? Also, nothing jumped out at me as an easy way to quit just XSOverlay from the SteamVR overlay.

**Comment by Xiexe** [comment]
Added to todo list.

**Comment by Xiexe** [comment]
This was sort of added as a task tray icon that can be used to exit the overlay from within the overlay, build 465.
