### ISSUE TITLE
Unable to grab windows with left hand. (Index)

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#63]
**Describe the bug in detail:**
Can't grab windows, nor the keyboard with the left hand.

**Provide steps to reproduce the bug:**
Always happens.

**Expected behavior:**
Move window/keyboard by grabbing it.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4478156/output_log.txt)

**Additional Information:**
Thought it was a problem with my bindings at first but the issue persists after setting them to the default.

**Comment by Xiexe** [comment]
This is on the beta branch since I reworked window movement, I'll be pushing a fix tonight!

**Comment by Xiexe** [comment]
Fixed in 286 Beta! Thanks for the report!
