### ISSUE TITLE
top windows bar and sides flicker when a window like Spotify is captured independently

### ISSUE THREAD

**Issue by djgeloofficial** [Xiexe/XSOverlay-Issue-Tracker#65]
**Describe the bug in detail:**
**Provide steps to reproduce the bug:**
**Expected behavior:**
https://youtu.be/wK0RQM0lMJ4

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4517004/output_log.txt)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4517022/uDesktopDuplication.log)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4517024/uWindowCapture.log)

**Additional Information:**
I had this happen with Microsoft Teams  and Discord.
https://youtu.be/ZPIF5r-vDbY
https://youtu.be/RGAXuo_ga0s
behavior is the same so it might be a issue of my windows.

**Comment by Xiexe** [comment]
Thanks for posting this here. Will look into it tonight or tomorrow. 

Was this an issue in previous builds?

**Comment by djgeloofficial** [comment]
Not at all.

**Comment by Xiexe** [comment]
After doing a bit of digging, it turns out that a specific windows 10 update caused this problem with the window capture API we are using. There was an update that got pushed recently by Microsoft that should have fixed this, according to other users.

**Comment by Xiexe** [comment]
Confirmed to be an issue with a Windows 10 update.
