### ISSUE TITLE
Window option accessible when the window is hidden

### ISSUE THREAD

**Issue by MMMaellon** [Xiexe/XSOverlay-Issue-Tracker#67]
**Describe the bug in detail:**
When I hide a window and then hit the button I have bound to the window options, I see the options appear where the window used to be.

**Provide steps to reproduce the bug:**
1. Install SteamVR Beta 1.11.11
2. Open XS Overlay and create a new window
3. Hide Window
4. Hit the window options button. You don't need to aim at the window.

**Expected behavior:**
The window options menu should only show up when the window is visible and when I'm pointing my hand at a window.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4521171/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4521172/uDesktopDuplication.log)

**Additional Information:**
I only tested this on SteamVR Beta 1.11.11

**Comment by Xiexe** [comment]
Add to todo list, overlooked an edge case.

**Comment by Xiexe** [comment]
Fixed in beta 304
