### ISSUE TITLE
Option to disable window aim

### ISSUE THREAD

**Issue by lithiumfrog** [Xiexe/XSOverlay-Issue-Tracker#70]
My window auto aiming and tilting based off of my head/controllers is great most of the time, but there are occasions, mostly when laying down, where I'd love to be able to aim/rotate/tilt/etc the window manually. Sometimes it just feels like I can't get the window exactly where I want it, and it can be pretty frustrating to fight with it.

tldr Would appreciate a toggle in the options to just make a window into a plain old "pick it up and place it wherever I want it without it adjusting itself" kind of window.

**Comment by Xiexe** [comment]
Coming in an upcoming beta build.

**Comment by Xiexe** [comment]
Added.
