### ISSUE TITLE
Full Screen Video Player taking mouse from other windows

### ISSUE THREAD

**Issue by SplitScream** [Xiexe/XSOverlay-Issue-Tracker#72]
**Describe the bug in detail:**
With 2 Windows Open:
Window A is fullscreen video
Window B is overlapping window
Clicking on overlapping Window B immediately interacts with fullscreen Window A

**Provide steps to reproduce the bug:**
Open any Youtube Video and make it fullscreen on Window A
Open any other Window with a separate window, such as alt-tabbing to make FullScreen Video in the background 

**Expected behavior:**
What do you expect to happen, rather than what does happen?
Window B should be clicked on instead of Window A taking full mouse from other windows

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the [issue.](url
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4741501/output_log.txt)
)

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment]
This should be fixed on the upcoming beta build.
