### ISSUE TITLE
Oculus touch controllers trigger only right clicks

### ISSUE THREAD

**Issue by shizzl3myznizzl3** [Xiexe/XSOverlay-Issue-Tracker#75]
the bug is as stated in the title i'm using the Oculus CV1 HMD with the touch controllers and before i updated to the beta client the main trigger was left click function and to left click i would need to hold b then press the main trigger now the main trigger is right click 
recreating the bug all that is needed to do is have a monitor overlay turned on then simply use the main trigger on the Oculus touch controllers (must be using the BETA client) 
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4887467/output_log.txt)

**Comment by Xiexe** [comment]
Make sure that you're not touching the face buttons when pulling the triggers! By default, those modify the trigger pull to do a right or middle click, depending on which face button you're touching! 

(I tested the bindings on my quest with the link cable before publishing the beta build!)

**Comment by Xiexe** [comment]
Oh, I see you closed the issue, woops.
