### ISSUE TITLE
Beta: Unable to select any wrist controls

### ISSUE THREAD

**Issue by bdunderscore** [Xiexe/XSOverlay-Issue-Tracker#76]
**Describe the bug in detail:**
Attempting to click any wrist control on the beta branch is broken. There is haptic feedback when the pointer goes over them but the trigger does nothing.

**Provide steps to reproduce the bug:**

1. Try to use any control on beta

**Expected behavior:**
Buttons should work?

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4894010/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4894012/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4894013/uDesktopDuplication.log)

**Additional Information:**
Using index controllers. I have a slightly customized binding profile that changes the activation hotkey - I am able to use that to enter edit mode, but again the wrist buttons don't work.

**Comment by Xiexe** [comment]
As the changelog suggests here:

https://steamcommunity.com/games/1173510/announcements/detail/2511268901733494617

You will need to set up your bindings again if you were not on the default bindings, as I had to change some stuff around, and wanted to make some things more clear on what they were. This will be the only and last time the bindings get changed.

**Comment by bdunderscore** [comment]
Ah... Missed that changelog I guess. I tried resetting my bindings but the "activate" button on the steam control binding interface didn't seem to have any effect, I guess I'll need to dig into that some more later.

**Comment by Murkur** [comment]
Cant reset my binding at all ive tried manually deleting it and the activate button doesnt do anything so im forced to use a older XS overlay version

**Comment by Xiexe** [comment]
A fix has been found and will be pushed tomorrow morning to beta branch for the bindings not being able to be reset. I will ping this thread one last time tomorrow morning when the fix is pushed and close the thread.

**Comment by Xiexe** [comment]
Fixed on beta 314! Patch was just pushed.
