### ISSUE TITLE
Scroll in wrong direction

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#79]
**Describe the bug in detail:**
Pushing the thumbstick very slightly causes the scroll to go in the wrong direction.

**Provide steps to reproduce the bug:**
At least on Index, push the thumbstick very lightly up or down.

**Expected behavior:**
Scroll in the correct direction.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4941818/output_log.txt)

**Comment by Xiexe** [comment]
This will be fixed in the next beta patch which will be rolling out soon.

**Comment by Xiexe** [comment]
Was fixed on beta
