### ISSUE TITLE
[183] Stuck on steamvr overlay after opening edit bindings

### ISSUE THREAD

**Issue by bdonlan** [Xiexe/XSOverlay-Issue-Tracker#8]
**Describe the bug in detail:**
Unable to close stream overlay after opening controller bindings using XSOverlay settings

**Provide steps to reproduce the bug:**
1. Use index controllers
2. Open bindings editor via XSOverlay settings
3. Press the system button on your controller

**Expected behavior:**
The steamvr overlay should close

**Actual behavior**
A screenshot is taken. The overlay can be closed by power cycling a controller.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

Will do when I get back home tonight.

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment]
Wow. That's a wild one. It takes a screenshot? 

Which version of SteamVR are you running currently? Beta? Live?

**Comment by bdonlan** [comment]
My guess is that releasing the trigger is being ignored somehow. I'm on live steamvr.

**Comment by Xiexe** [comment]
This would've made a lot more sense on beta, since there's the input stealing stuff now, I could see that potentially having caused a problem.

Hmm, out of curiosity, could you try using the beta and seeing if the same issue happens?

**Comment by bdonlan** [comment]
I'll play around with it a bit tomorrow!

**Comment by bdonlan** [comment]
Logs attached before I forget and overwrite them: [output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4190132/output_log.txt)

**Comment by Xiexe** [comment]
I just tested on the SteamVR beta, and it seems to be working fine there. Might be an issue with current SteamVR builds.

**Comment by bdonlan** [comment]
Some more info:

1. Reproducibility is not 100% but is quite high (>50%)
2. Pulling the trigger a couple times can also close the overlay it seems.

**Comment by Xiexe** [comment]
closing due to belief of a steamvr bug; don't think its on my end. will reopen if we come to find that it is indeed on my end
