### ISSUE TITLE
I cant use the overlay

### ISSUE THREAD

**Issue by PeEzZ96** [Xiexe/XSOverlay-Issue-Tracker#80]
After the latest update, i cant open the menu of the overlay in VR, only with the binded button, but i cannot acces it, i mean, i cant press any button on my wrist.

I tried to reinstall the overlay, but it did not help.

Log:
`Initialize engine version: 2018.4.16f1 (e6e9ca02b32a)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 Ti (ID=0x1b06)
    Vendor:   
    VRAM:     11127 MB
    Driver:   27.21.14.5167
Begin MonoManager ReloadAssembly
- Completed reload, in  0.101 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.730100 ms
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.175500 ms
<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Build : 316
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Trying to create Music thread.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Music thread successfully started.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Loaded config file from: C:/Users/Dani/AppData/LocalLow/Xiexe/XSOverlay/config
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Saved config to: C:/Users/Dani/AppData/LocalLow/Xiexe/XSOverlay/config
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Saved config to: C:/Users/Dani/AppData/LocalLow/Xiexe/XSOverlay/config
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | Saved config to: C:/Users/Dani/AppData/LocalLow/Xiexe/XSOverlay/config
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:30 | File for Simulation controls already exists! Initializing...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

[DRP] Starting Discord Rich Presence
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

[DRP] Discord Rich Presence intialized and connecting...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 10 unused Assets to reduce memory usage. Loaded Objects now: 11948.
Total: 19.281600 ms (FindLiveObjects: 0.728000 ms CreateObjectMapping: 0.157100 ms MarkObjects: 18.319200 ms  DeleteObjects: 0.076600 ms)

Created new NamedPipeClientStream 'discord-ipc-0' => '\\.\pipe\discord-ipc-0'
<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Toggling wrist overlay True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Loading default Keyboard layout.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Serialization depth limit 7 exceeded at 'Key.childKeys'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
8: Key.childKeys
7: Key.childKeys
6: Key.childKeys
5: Key.childKeys
4: Key.childKeys
3: Key.childKeys
2: Key.childKeys
1: Key.childKeys
0: Keys.key

 
(Filename:  Line: 128)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Saved config to: C:/Users/Dani/AppData/LocalLow/Xiexe/XSOverlay/config
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Detected System Language: hu
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Found Localization File: D:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/en.json
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Found Localization File: D:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/es.json
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Found Localization File: D:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/localization/ja.json
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Layout Directory is: D:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets/Layouts
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Device LeftTracker subscribed to events for LeftHand!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Device HMD subscribed to events for Head!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Device RightTracker subscribed to events for RightHand!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Loaded Index UI Elements.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Checking to see if SteamVR Is Running...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Starting Up SteamVR Connection...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[SteamVR]</b> Initialized. Connected to lighthouse:LHR-0598C798
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[SteamVR]</b> Successfully loaded 23 actions from action manifest into SteamVR (D:/Program Files (x86)/Steam/steamapps/common/XSOverlay_Beta/XSOverlay_Data/StreamingAssets\SteamVR\actions.json)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Connected to SteamVR!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | SteamVR Version: 1.14.1
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Current Tracking Universe: TrackingUniverseStanding
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Recentering Window Space.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Overlay Created! JoystickUI
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Loaded simulation mode bindings...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | HMD Type: generic_hmd
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Overlay Created! JoystickUICursor
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:31 | Overlay Created! Wrist Overlay Attached
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

[DRP] Disposing Discord IPC Client...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

[DRP] Finished Disconnecting
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:32 | Overlay Created! Raycaster.RightTracker.VisualCursor
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:37 | Detected Headset Refresh Rate: 144
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:37 | Loaded Tracker UI elements.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:42 | Song was changed to No music player found
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:42 | Fading Song Title Out...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:40:42 | Fading Song Title In...
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:41:51 | Release control of input.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:41:54 | Release control of input.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:41:59 | Release control of input.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:41:59 | Release control of input.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:42:03 | Toggling Layout Mode to True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:42:03 | Overlay Created! Toolbar_Overlay(Global)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:42:03 | Overlay Created! Toolbar_Overlay(Window)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:42:03 | Taken control of input.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:42:08 | Toggling Layout Mode to False
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

<b>[XSOVR]</b> | 2020. 07. 20. 18:42:08 | Release control of input.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

`

**Comment by Xiexe** [comment]
Please refer to this announcement I made.

https://steamcommunity.com/games/1173510/announcements/detail/4119055961243467398

**Comment by Xiexe** [comment]
Will be closing this issue shortly
