### ISSUE TITLE
clock stuck on 24 hour

### ISSUE THREAD

**Issue by jettsd** [Xiexe/XSOverlay-Issue-Tracker#82]
**Describe the bug in detail:**
the wrist clock displays in 24 hours by default it can be changed to 12 hour but changes itself back to 24 hour on restart

**Provide steps to reproduce the bug:**
as above

**Expected behavior:**
for it to stay on 12 hour on reset

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4962389/output_log.txt)

**Additional Information:**
none

**Comment by Xiexe** [comment]
Noted!

**Comment by Xiexe** [comment]
This *should* be fixed since the last beta.

**Comment by Xiexe** [comment]
Closing issue as it's been inactive and I believe it to be fixed.
