### ISSUE TITLE
snapping windows together

### ISSUE THREAD

**Issue by Yui-Hell** [Xiexe/XSOverlay-Issue-Tracker#85]
**Feature Description:**
snapping windows together like have something were if you bring 2 windows close to eachother thay can snap and line up its really nice on multi window setups

**Comment by Xiexe** [comment]
I'm thinking of ways to implement this - the infrastructure for snapping is there, however, if I add window snapping I'd also like to add an interface for adjusting the angle it's snapped at afterwards.
