### ISSUE TITLE
Window collider not curving when entering edit mode

### ISSUE THREAD

**Issue by IncompatibleW** [Xiexe/XSOverlay-Issue-Tracker#86]
**Describe the bug in detail:**
When you have a curved window, leaving and entering edit mode will reset the window collider to flat instead of curved.

**Provide steps to reproduce the bug:**
Open a curved window, then leave edit mode. Open edit mode again and move cursor to the edge of the window.

**Comment by Xiexe** [comment]
Fixed in next build
