### ISSUE TITLE
Window configuration buttons stay visible when all windows are closed

### ISSUE THREAD

**Issue by bdunderscore** [Xiexe/XSOverlay-Issue-Tracker#87]
**Describe the bug in detail:**
When you exit edit mode, the controls shown below windows stay stuck onscreen.

**Provide steps to reproduce the bug:**
1. Open a window. Don't pin it.
2. exit edit mode

**Expected behavior:**
What do you expect to happen, rather than what does happen?
All controls should vanish, but instead some UI elements stay onscreen.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5009818/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5009819/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5009820/uDesktopDuplication.log)

**Additional Information:**
Provide any additional information here.

**Comment by bdunderscore** [comment]
https://www.youtube.com/watch?v=6pRjMEAfc4g

**Comment by Xiexe** [comment]
Known issue with 352 and will be fixed tomorrow along with all the other stuff reported in the beta feedback channel!

**Comment by Xiexe** [comment]
Fixed in next build
