### ISSUE TITLE
Support for JP109 keyboard layout.

### ISSUE THREAD

**Issue by yanorei32** [Xiexe/XSOverlay-Issue-Tracker#88]
**Feature Description:**
XSOverlay supports key remap by JSON.
However, there are more keys in keyboards that we use, and some key positions are different.

JP109 keyboard layout
 https://commons.wikimedia.org/wiki/File:KB_Japanese.svg

While there already exists a fan-made JP keyboard layout, it lacks some keys.
 https://twitter.com/eco_chii/status/1293506203696246786

I would like our keyboard layout supported.

**Comment by Xiexe** [comment]
Hi!

I have plans to soon expand the keyboard and keyboard editing functionality pretty heavily! 

It's next on the list of the UI 2.0 overhaul stuff that I've been working on! 

Once this next update comes out of beta, the keyboard overhaul will be happening directly after that! 

Ideally the tools I will be exposing for customization will just allow you to make whatever you want in terms of a layout! ^_^
