### ISSUE TITLE
Keyboard gets stuck until XSOverlay restarts

### ISSUE THREAD

**Issue by lyuma** [Xiexe/XSOverlay-Issue-Tracker#9]
**Describe the bug in detail:**
Some time after using XSOverlay, the keyboard stops being able to move, and the button to close and reopen the keyboard doesn't teleport it near the user.

**Provide steps to reproduce the bug:**
Use XSOverlay for a while. Using lots of advanced settings to move around the room. I tend to destroy all windows and create new windows regularly because I'm not used to the teleport button.

**Expected behavior:**
Keyboard should always be pickup-able, and the button to reopen the keyboard should spawn it near the user.

**Output Log:**
Attached
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4193064/output_log.txt)

**Additional Information:**
This has been happening for months across various XSOverlay builds, previously called a "Soft lock" issue. I'm no longer getting the "Soft lock" but this bug still happens.

**Comment by PhaxeNor** [comment]
[output_log - Copy.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4193192/output_log.-.Copy.txt)

**Comment by Xiexe** [comment]
Fixed in 191 +

**Comment by lyuma** [comment]
[output_log_stuckkeyboard2.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4206078/output_log_stuckkeyboard2.txt)
Ran into the bug again... build 196

The session was running for a long time. I lost the keyboard so cannot confirm if dragging works but double tapping keyboard button did nothing.

**Comment by Xiexe** [comment]
I'm going to assume this is actually a new issue, same as #13, as it sounds the same to me.

**Comment by PhaxeNor** [comment]
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4209402/output_log.txt)
Same, regression?
