### ISSUE TITLE
Monitor view crashes / becomes unresponsive

### ISSUE THREAD

**Issue by Kosyne** [Xiexe/XSOverlay-Issue-Tracker#92]
My panel layout is typically 1 panel for each of my monitors (1080p for one, 4k for the other).

Multiple times for every single VR session, one of the panels will randomly stop responding. It won't update anymore, and the cursor looks like glitchy graphics. This is a very, very frequent issue.

Regarless of disabling/enabling the pane, switching monitors, etc, that monitor remains permanently bugged the rest of the VR session. I can however select individual windows that are on the affected monitor.

I used to be able to work around this issue by toggling the affected panel from one monitor, to the other, and back again, hitting the refresh/reload button at each step. However, the refresh button has been taken out, making one of the panes permanently useless.

I am on Windows 10, Valve Index.

I have a number of background programs running, such as wallpaper engine, OBS, unity, blender, Hyper-V, and others, if that has any bearing on it.

I just started up VR so I have no relevant logs at time of writing, but will add them when it happens again.

**Comment by Xiexe** [comment]
Toggling layout mode should force all monitor captures to refresh. That's why there's a small hitch when you toggle layout mode now. 

The refresh button was removed because it was streamlined.

**Comment by Xiexe** [comment]
Closing as this issue was resolved and explained more in depth via. Discord. 

The issue of monitor captures freezing is due to a VRAM requirement, and is especially prevalent when you have a 4K monitor, of which capturing takes a lot of VRAM. 

The new capture APIs will have the option hopefully to limit the texture resolution, which should alleviate this.
