### ISSUE TITLE
When placing cursor on keyboard, cursor starts from the last position it was at before snapping to the actual position

### ISSUE THREAD

**Issue by s-ilent** [Xiexe/XSOverlay-Issue-Tracker#94]
**Describe the bug in detail:**
When placing a cursor on the keyboard, it doesn't appear at the place that the controller is pointing at. Instead, the cursor starts from the last cursor position and then snaps to the new one. This seemingly causes misclicks when selecting, for example, Ctrl/Alt keys, where you may move the cursor off the keyboard while going to hit the Ctrl key, and subsequently  go to click it and end up toggling Alt instead. 

**Provide steps to reproduce the bug:**
1. Place one cursor on the keyboard.
2. Move the cursor off the side of the keyboard.
3. Watching the original position, move the cursor back on the keyboard,

**Expected behavior:**
I think this causes some problems when typing fast, because it makes hitting the Ctrl/Alt keys at high speeds unreliable. It's possible to move the cursor fast enough to be close enough to a button and hit the wrong one when the position updates. If you move the cursor back and around repeatedly (i.e. in a U shape), it kind of freaks out.

**Output Log:**
N/A

**Additional Information:**
Provide any additional information here.
N/A

**Comment by Xiexe** [comment]
Fixed in b388+
