### ISSUE TITLE
Unwanted screen blocker

### ISSUE THREAD

**Issue by Dav-Edward** [Xiexe/XSOverlay-Issue-Tracker#97]
**Describe the bug in detail:**
Newest version puts a very annoying window telling me to put on my headset completely blocking view to my desktop. I get it, put on the headset. Please don't make a fullscreen window I can't minimize that blocks the entire view of my desktop so when I switch out of headset I can't use my desktop at all, nor use Steam desktop control for when in VR games that are too sensitive to body movements and trigger pulls to safely do certain desktop tasks.

PLEASE get rid of that annoying screen blocker. I had to uninstall because my computer is unusable while XSOverlay is running now.

**Expected behavior:**
A **small** hint window telling you to put on the VR headset to use XSOverlay that you can minimize

Addition: This is incredibly annoying for us that do development or Twitch/YouTube streaming

**Comment by Dav-Edward** [comment]
![image](https://user-images.githubusercontent.com/7320237/99733717-3569a680-2a87-11eb-9070-e041fd413692.png)
This shouldn't take up the entire screen every time I go into VR

**Comment by Xiexe** [comment]
That window should minimize itself and is 100% minimize-able. If it doesn't, resizing the window will make it keep that size. Did you accidentally hit f11 on it to force it into full screen at some point? 

Either way, I'm looking in to ways to entirely get rid of the Unity desktop window anyways. I've always hated it, it's always annoying, and it always had eaten up extra cpu even if it doesn't render anything. Trust me, I'm on the same page.

Currently, there's a bug with the engine version I'm using though that prevents the window from being hidden entirely.

**Comment by Xiexe** [comment]
Correction to my post - It seems that Disallowing full-screen in Unity means that F11 doesn't work, but Alt + Enter *does* still work, for some dumb reason.

**Comment by Xiexe** [comment]
Update 2: I went ahead and updated Unity version, and that fixed the main problem that was forcing me to keep the window around. There will now no longer be a desktop window, soon tm.

**Comment by Dav-Edward** [comment]
Thanks for the updates Xiexe, I'll try what you suggested as soon as I get my headset out next opportunity. The XSOverlay was always a tiny window for me until a recent update which took me by surprise when the above picture I sent is all my desktop shows whenever I fire up XSOverlay which is super annoying as it covers everything, even the Windows task bar. Alt-Tab can bring other windows in front but it otherwise covers the whole screen.

I'll give alt+enter a shot and F11 too just in case to see if I can get it to shrink back down. I'll follow-up with my results.

**Comment by Dav-Edward** [comment]
I realized I can run XSOverlay without needing to pull out my headset and gave it a try. Alt-Enter worked! Thank goodness!
Thanks for your help Xiexe
